### ISSUE TITLE
onClick broken on iOS.

### ISSUE THREAD

**Issue by leebyron** [facebook/react#134]
iOS Safari really doesn't want you clicking anything that's not an `<a>` tag. This is a known issue: http://stackoverflow.com/questions/5421659/html-label-command-doesnt-work-in-iphone-browser/6472181#6472181

The way you fix this is by putting an empty "onclick" attribute on nodes you wish to emit click events. Yep.

So presumably:

```
div({onClick: function(){alert('clicked');}}, 'click me');
```

should emit:

```
<div onclick>click me</div>
```

on iOS. Ensuring that the click event is actually reachable from an iOS device.

As the stack overflow link points out, this is also an issue for `<label>` elements associated with `<input>` elements. In order to behave as a clickable label, they must also include an empty "onclick" attribute.

```
label(null, input({type: 'checkbox'}), check me);
<label onclick><input type="checkbox> check me</label>
```

**Comment by mietek** [comment]
This is still an issue in 0.13.3.

**Comment by spicyj** [comment]
It's fixed in 0.14 beta and will be in the final 0.14 as well.

**Comment by shuson** [comment]
The ```<a>``` without ```href``` attribute but with onClick event doing the navigation is not working across all kinds of browsers in iOS platform. (I test 4 of them in iOS 8.4.1 :)
But if we put a styling ```cursor:pointer``` for ```<a>```, it will bypass iOS' restriction of the press and hold copy and paste text mechanics.

**Comment by yagudaev** [comment]
Just had the same problem with an `onClick` event on an overlay that was suppose to dismiss a menu when clicked or tapped. Changing the style to `cursor: pointer` like @shuson said worked, but it shouldn't be required.

**Comment by spicyj** [comment]
As I said, this is fixed in 0.14 which will be released soon.

**Comment by uzarubin** [comment]
We are currently having this issue only on iOS 9. The workarounds work for other versions of iOS, just not the most recent one. Is anyone else experiencing this?

**Comment by spicyj** [comment]
@uzarubin Haven't heard of this. I just tested with http://react.jsbin.com/vovuzexiza/edit?html,js (http://react.jsbin.com/vovuzexiza) and it seems to work fine.

**Comment by melbayad** [comment]
I'm currently using React v0.14.0 and still have the same issue (event click not firing) on Safari v8.0.6 and IE. I've added `cursor:pointer` but with no luck. can you please help me to make it work ?

**Comment by spicyj** [comment]
This issue has been fixed. If you're seeing the wrong behavior from React still, please open a new issue with a minimal repro case.

**Comment by tiaaaa123** [comment]
`react: 15.1.0` Still not working. I have the cursor: pointer as you can see. I tried `onTouchStart`, `onTouchTap` and `onClick` but none is happening.

 <div
      onTouchStart={() => alert('hi')}
      onTouchTap={() => alert('hi')}
      onClick={() => alert('hi')}
      style={{ padding: '16px', color: 'black', fontSize: '25px', cursor: 'pointer' }}>
           Click me!
  </div>

When I'm on my website on an IPad and and my laptop the click on the IPad does nothing on the IPad, but it does on PC! The even seems to be triggered, but nothing is displayed on IPad....

**Comment by stresslimit** [comment]
I love that this was still relevant to me today, thank you internet archives!
