### ISSUE TITLE
Function components do not support contextType.

### ISSUE THREAD

**Issue by olalonde** [facebook/react#14061]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Warning: withRouter(RegisterModal): Function components do not support contextType.

**What is the expected behavior?**

No error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.6.0

https://codesandbox.io/s/01zl4m022v

Unfortunately, I'm unable to reproduce this in codesandbox...

```javascript
import React, { Component } from "react";
import { withRouter } from "react-router-dom";
import ErrorContext from "./ErrorContext";

class RegisterModal extends Component {
  render() {
    return <div>test</div>;
  }
}

RegisterModal.contextType = ErrorContext;

// this doesn't cause any error:
// export default RegisterModal;
// this causes an error:
export default withRouter(RegisterModal);
```

For some reason, whenever I wrap my RegisterModal component with withRouter, I get this error: `Warning: withRouter(RegisterModal): Function components do not support contextType.`. The weird thing is I'm setting contextType directly on the class, before the HOC function is applied.

**Comment by olalonde** [comment]
This appears to get rid of the error for some reason:

```javascript
const WrappedClass = withRouter(RegisterModal);
WrappedClass.WrappedComponent.contextType = ErrorContext;
export default WrappedClass
```

**Comment by gaearon** [comment]
Are you using static class properties syntax?

**Comment by pmacmillan** [comment]
@olalonde 

Reproducable: your sandbox includes react-dom@16.5.2. Upgrading to match react@16.6.0 and the error message appears.

The problem is that https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/withRouter.js blindly copies all statics up to the function based HOC ("C") including the new contextType static.

Likely fix is to have withRouter avoid this with respect to contextType.

**Comment by gaearon** [comment]
My best guess is that React Router copies the `contextType` from the inner class because it's static. That was fixed in https://github.com/mridgway/hoist-non-react-statics/pull/62 so you should get the fix automatically when you update the lockfile.

**Comment by gaearon** [comment]
https://github.com/mridgway/hoist-non-react-statics/pull/62 fixes this.

**Comment by kiranvj** [comment]
Updated hois-non-react-statics to 3.1.0. Still I could see the warning.

**Comment by bjm88** [comment]
was usings contextType = ThemeContext for example on my component as context api suggests, was on react 16.6.1 and it still had this issue...

**Comment by nickdb93** [comment]
@bjm88 Yes, I'm still having this issue as well.

**Comment by kiranvj** [comment]
Yes, the issue persists even after updating hoist-non-react-statics. See the issue discussed [here](https://stackoverflow.com/questions/53240058/use-hoist-non-react-statics-with-withrouter)

**Comment by amwill04** [comment]
Seems to have been resolved once I upgraded to `reeact-router-dom v4.3.1`

**Comment by techyrajeev** [comment]
Is there any solution to this issue?
I just updated to 16.6.0 but still facing this issue.
Please suggest any possible working solution.

**Comment by leonadler** [comment]
@kiranvj @techyrajeev 

You can use an intermediate Component (function or class) that does not have a `contextType` and which in turn renders your component which needs the router:

```javascript
export function withRouterWorkaround(Inner) {
    const Wrapped = (props) => <Inner {...props}/>;
    Wrapped.displayName = `WithRouterWorkaround(${Inner.displayName || Inner.name || '?'})`;
    return withRouter(Wrapped);
}
```
or as a class
```javascript
export function withRouterWorkaround(Inner) {
    class Wrapped extends Component {
        render() {
            return <Inner {...this.props}/>;
        }
    }
    Wrapped.displayName = `WithRouterWorkaround(${Inner.displayName || Inner.name || '?'})`;
    return withRouter(Wrapped);
}
```

TypeScript:
```typescript
export function withRouterWorkaround<P extends RouteComponentProps<any>>(
  Inner: ComponentType<P>
): React.ComponentClass<Omit<P, keyof RouteComponentProps<any>>> {
  const Wrapped: FunctionComponent = (props: any) => <Inner {...props} />;
  Wrapped.displayName = `WithRouterWorkaround(${Inner.displayName || Inner.name || '?'})`;
  return withRouter(Wrapped as any);
}
```

**Comment by frani** [comment]
the next code works for me
```javascript
static contextType = MyContext

...

export default Object.assign(withRouter(MyComponent), { contextType: undefined });
```

**Comment by ahmedalima** [comment]
> Is there any solution to this issue?
> I just updated to 16.6.0 but still facing this issue.
> Please suggest any possible working solution.

you can delete the static variable from the wrapped class and keep the static property in the innerComponent only
for example:
you can assign static variable like this:
`IssueRowPlain.contextType = UserContext;`
wrap the component
`const IssueRow = withRouter(IssueRowPlain);`
then delete the static variable from result wrapped component
`delete IssueRow.contextType; `
