### ISSUE TITLE
Input type email bug

### ISSUE THREAD

**Issue by dominicarrojado** [facebook/react#14168]
https://codepen.io/anon/pen/GwZeNO

Open this codepen and paste this "example@gmail.com 1"
Then press backspace, notice that the focus changes to the beginning of the input.

**Comment by Xizario** [comment]
It happens because the browser trim the spaces from the end of the value. Modify your code as follows to see what happens:
```jsx
  inputOnChange = ({ target }) => {
    console.log('\'' + target.value + '\'');
    this.setState({ [target.name]: target.value });
  }
```

Looks already discussed here https://github.com/facebook/react/issues/6368

**Comment by deammer** [comment]
This means we have to choose between using an uncontrolled input with `type="email"` _or_ a controlled input with `type="text"`, which isn't great.

My "solution" is to swallow the event if it's a space:

```js
// Controlled email input
<input
  type="email"
  value={this.state.value}
  onChange={this.onChange}
  onKeyPress={this.onKeyPress} />

onKeyPress = syntheticEvent => {
  if (syntheticEvent.charCode === 32) {
    syntheticEvent.preventDefault();
  }
}

onChange = evt => {
  this.setState({ value: evt.target.value });
}
```

This won't work if a user pastes an email with a space in it, but it's the least terrible bandaid I could come up with 🙈

**Comment by oliviertassinari** [comment]
A similar issue was reported on Material-UI side. The regression seems to have come between React v16.2.0 and v16.3.0: https://codesandbox.io/s/xrv5w1j90w.

**Comment by nataliemarleny** [comment]
I've narrowed down to where this problem was introduced - it first appears 
because of the changes in [`4338c8db` commit to the file 
`src/renderers/dom/shared/HTMLDOMPropertyConfig.js`][1]. If the changes from 
this commit/file are reverted in any of the commits that come after it, `<input 
type="email">` no longer has this strange behaviour.

As I can see in `packages/react-dom/src/shared/DOMProperty.js` in the master branch, 
there aren't any markers to denote that a prop has side-effects anymore, so 
purely reverting to fix this problem doesn't seem straightforward.


[1]: https://github.com/facebook/react/commit/4338c8db4b03cb1ba5f2e229b1baa5a848fe65ab#diff-5a2abece6f8c2495d8242daa40245434

**Comment by LucasDachman** [comment]
I'm still getting this bug on React 16.12.0

**Comment by Avadakedvr** [comment]
> I'm still getting this bug on React 16.12.0

same here, any fixes?

**Comment by josepharhar** [comment]
I made a fix in chrome which should fix this problem which should be released in chrome 85, try it out on canary: https://www.google.com/chrome/canary/

**Comment by JCC13** [comment]
Hi, I'm still seeing this issue on React v16.13.1. Seeing it on Chrome browser. Anyone here observed the same on the latest React version 16.13.1? Someone here has the fix for this issue? Thanks.

**Comment by josepharhar** [comment]
@JCC13 Did you try it in chrome canary? The fix is not in stable chrome yet.

**Comment by josepharhar** [comment]
@gaearon I believe this issue is fixed.
- Firefox: I believe this never affected firefox
- Chrome: The fix is now in stable chrome
- Safari: I just landed a fix to webkit

**Comment by deammer** [comment]
@josepharhar I can confirm that this bug is fixed in Chrome 86 with React 16.13.1.

https://codepen.io/deammer/pen/rNLZzyV

**Comment by sophiebits** [comment]
This was fixed in Chrome 85 in 2020.
