### ISSUE TITLE
Cursor in controlled input field jumps to beginning when typing a sharp S (ß)

### ISSUE THREAD

**Issue by Bastian** [facebook/react#14356]
**Do you want to request a *feature* or report a *bug*?**

Report a  bug

**What is the current behavior?**

In Chrome, when typing a sharp S (ß, a German letter) in an input field with `type="email"`, it converts the `ß` to `ss` (expected behaviour) and the cursor jumps back to the beginning of the input field (unexpected behaviour). This does only happen if the `ß` is part of the domain.
Trying to type `test@testß.de` will end as `.detest@testss`:
![Example](https://i.imgur.com/SWQ0p4f.gif)

It can be tested with the latest Google Chrome: 
https://codepen.io/anon/pen/MzzEqB
If you don't have a `ß` on your keyboard, you can reproduce the bug by just Copy&Pasting it.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested with Chrome Version 70.0.3538.110 (Official Build) (64-bit) on Ubuntu 18.04 and React 16.6.3

In Firefox, this does not happen, as it does not convert `ß` to `ss`. I didn't test other browsers.

**Comment by philipp-spiess** [comment]
@Bastian thanks for reporting. I can reproduce this behavior as well. Does not seem to happen on a native `email` field: https://codesandbox.io/s/mz5669rwyy

I think the next step is to find out which DOM APIs we're calling to cause this invalid state and see if this is a Chrome bug or something that we're doing wrong. Do you want to look into this? 🙂

**Comment by Bastian** [comment]
Thanks for confirming the bug. I'll look into it :)

**Comment by Bastian** [comment]
After some investigation, I don't think it is possible to fix this on React's side.
Calling `element.value` already converts the `ß` to `ss` and there seems to be no way to see the "real" content of the input field. So using this value to append new letters causing the `ß` to be replaced by `ss`.

See https://codesandbox.io/s/ovv5zkzm05

**Comment by xuzhanhh** [comment]
I found ß will convert to ss after 'someword@' in Chrome 70.0.3538.110 macOS 10.13.6 (17G65)

**Comment by philipp-spiess** [comment]
@Bastian Thanks for checking this out 👍 

It seems like the conversion on `element.value` is the spec-conform behavior: The `.value` of an `email` input should be [punycoded](https://en.wikipedia.org/wiki/Punycode):

> User agents should convert punycode in the domain labels of the value to Internationalized Domain Names in the display, and vice versa.

See [this Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=410937) and [the HTML spec](https://www.w3.org/TR/html52/sec-forms.html#email-state-typeemail).

This appears to only be the case in Chrome though, the value won’t be punycoded in Safari, Firefox, and Edge. 

One interesting aspect here is the _"vice versa"_. Indeed, setting the `.value` to something like `foo@xn--c1yn36f.com` will appear as `foo@點看.com` in the input field in Chrome.

I found bugs with that as well. E.g. `foo@xn--ls8h.com` won’t appear as `foo@💩.com` although the `.value` of the latter will be puny-coded. This results in the same bug that you’re seeing for `ß` in React controlled inputs.

Maybe this is fixable on our side. Check out this example which sets `input.value` to `input.value` and doesn’t cause the `ß` to be converted (although the `.value` will report it punycoded): https://codesandbox.io/s/7wq72ol78q

I’m not super familiar with the code for controlled inputs but a next step here would be to step through the instructions and find out what we do that causes the input to break. Maybe this won’t be necessary when some [React Fire](https://github.com/facebook/react/issues/13525) changes are in as we’re probably going to make controlled components a lot easier.

**Comment by Bastian** [comment]
> Maybe this is fixable on our side. Check out this example which sets `input.value` to `input.value` and doesn’t cause the ß to be converted (although the `.value` will report it punycoded)

Yes, but as soon as you try to alter the input in any way, you run into problems. Just adding `toLowerCase()` will already cause issues again. Even tho I think this time it's a Chrome-Bug:
https://codesandbox.io/s/p73737253j

My only modification was to add `.toLowerCase()` and if you try to type something like `foo@TEßT.DE`, it will behave very weird and end as `foo@teßt.DE`:
![](https://i.imgur.com/pcSQQLF.gif)
Also notice that the `T` is upper case first and then will be converted to lower case after typing the point.

**Comment by alexrussell** [comment]
Seems to be checking if the format is valid as an email address and doing the unicode normalisation *only* if so.

When the value does correctly validate (e.g. `xxx@yyy` or `xxx@yyy.zz` but not `xxx@yyy.`), you get the disparity between normalised value and non-normalised display and thus lose the lowercasing effect on the display, which is why `xxx@yyy` works (no unicode to normalise, so no disparity, so lowercasing works), xxx@yyyßZZZ doesn't (unicode is normalised, creating a display disparity, so the lowercasing doesn't show) but then as soon as you add a `.` at the end, the email is invalid so no unicode normalisation happens, so the lowercasing suddenly works as there's no disparity. Interesting case!

**Comment by josepharhar** [comment]
I made a fix in chrome which should fix this problem which should be released in chrome 85, try it out on canary: https://www.google.com/chrome/canary/

**Comment by Bastian** [comment]
I can confirm that this fixes the bug.
Here's an updated codesandbox, as the old one seems to be broken: https://codesandbox.io/s/busy-meitner-45533

However, I still get a bug (less severe), when I try to modify the input. This happens when I try to modify the input with (in this example `.toLowerCase()`):
![email-input](https://user-images.githubusercontent.com/5033001/85064407-d0461800-b1ab-11ea-978c-c02dd5a0a208.gif)
 https://codesandbox.io/s/eloquent-torvalds-wg0ey
I was typing the following text on my keyboard: `FOO@TEßT.DE ABC`

This has nothing to do with React though and also happens with plain Javascript (see cosesandbox https://codesandbox.io/s/p73737253j from https://github.com/facebook/react/issues/14356#issuecomment-443495724).

**Comment by sophiebits** [comment]
This was fixed in Chrome 85 in 2020.
