### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by sagar-gavhane** [facebook/react#14484]
**Do you want to request a *feature* or report a *bug*?**

Bug 🐛🐛 (May be 🤔🙄)

**What is the current behaviour?**

I have created react function component and implement state full login using react hooks but it throws an `TypeError: Object(...) is not a function`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Installed packages
```json
"dependencies": {
  "@reach/router": "^1.2.1",
  "formik": "^1.4.1",
  "prop-types": "^15.6.2",
  "react": "^16.7.0-alpha.2",
  "react-dom": "^16.7.0-alpha.2",
  "react-scripts": "2.1.1",
  "styled-components": "^4.1.3",
  "yup": "^0.26.6"
},
```
Github repository : https://github.com/sagar-gavhane/workbench-client
Website: https://wonderful-allen-a3058d.netlify.com/
Screenshot: 
![screenshot](https://i.ibb.co/VLKVtNZ/Screenshot-from-2018-12-22-18-19-56.png)

**Comment by nikilok** [comment]
@sagar-gavhane you got a few glitches in your project setup.
/src/components/Input/input.js

Line 1 should be
import Input from './Input.jsx'

/src/screens/auth/Login/Login.jsx
Line 1 should be
import Input from '../../../components/Input/input.js'

and in package.json
use
"react": "next",
"react-dom": "next",

You should be good after that.

**Comment by VdustR** [comment]
`16.7.0`(`latest`) is not with hooks yet. Use `16.7.0-alpha.2`(or `next`) instead for now.

FYI [React v16.7: No, This Is Not The One With Hooks](https://reactjs.org/blog/2018/12/19/react-v-16-7.html).

**Comment by pungggi** [comment]
> `16.7.0`(`latest`) is not with hooks yet. Use `16.7.0-alpha.2`(or `next`) instead for now.
> 
> FYI [React v16.7: No, This Is Not The One With Hooks](https://reactjs.org/blog/2018/12/19/react-v-16-7.html).

very confusing..

**Comment by WillSquire** [comment]
Had to use `next` instead of `16.7.0-alpha.2` also, is this expected behaviour?

Really wanted a specific version in `package.json` instead of `next`.

**Comment by JNaeemGitonga** [comment]
Hey guys! How are you guys using `next` to use hooks? FB says they aren't even releasing yet and that it will be a few months, [read here](https://reactjs.org/blog/2018/12/19/react-v-16-7.html).

**Comment by ctur** [comment]
The link you have passed already says that?  @JNaeemGitonga

**Comment by JNaeemGitonga** [comment]
@ctur can tell you didn't read the question.

**Comment by EdmundsEcho** [comment]
FYI - using `16.7.0-alpha.2` _should_ work as an entry into the `package.json`.  However, in my experience, only when I changed the entry to `next` (per the advice above), did the error go away.  

Note, I also deleted my `yarn.lock` and `node_modules` for good measure.

**Comment by gaearon** [comment]
(But 16.8 is the first *stable* version to have Hooks)

**Comment by volkanunsal** [comment]
I just started getting this error in production. It doesn't happen in development, though. I'm using 16.8.x. Can anyone shed light on what is actually causing it?

**Comment by gaearon** [comment]
This error might happen if you use old React. It's not even a React error — you're calling `React.useState()`, and if that doesn't exist (such as in old versions), it's like calling `React.lalalala()`. The function doesn't exist, so you're calling `undefined()` and it crashes.

It might also happen if you call a non-existent method on some other library.

**Comment by volkanunsal** [comment]
Thanks, Dan!

**Comment by steelx** [comment]
I was getting the same erorr, but then I released I was using `createState` instead of `useState`

**Comment by merveillevaneck** [comment]
Hey! came across this while having a very similar issue except ive checked all the solutions and it doesnt seem to solve the problem. I'm very new to functional paradigms and react(and even javascript), what else should i try to investigate?  

I've got a lambda function as a component which has a body that starts off by generating some hooks. but it looks like the lambda isnt recognised, even though all my other components are lambdas too and they seem to work fine

**Comment by corysimmons** [comment]
Might help someone: Make sure you aren't `import { Foo } from 'Foo'` when you should be `import Foo from 'Foo'`. That is... this error is actually pretty descriptive and you can confirm it by commenting out the erroring out code, then doing something like `console.log(typeof Foo)` to see if it is an actual function or if it's something completely different.

**Comment by Tony1106** [comment]
I have the same error and just figure it out. The problem is when you copy the code from the demo site, this line is not correct: 

`import { makeStyles } from '@material-ui/core/styles';`

Change to this one: 

`import { makeStyles } from "@material-ui/styles";`

Check the docs from [here](https://material-ui.com/styles/basics/)

**Comment by Vijay-Barve** [comment]
try this
npm install rxjs@6.3.3 rxjs-compat@6.3.3 --save

**Comment by EdDevs2503** [comment]
Hey, your problem is complicated, but i could resolvet. You problem is React version. run this command: npm install react@next react-dom@next --save

**Comment by eebasadre20** [comment]
> Hey, your problem is complicated, but i could resolvet. You problem is React version. run this command: npm install react@next react-dom@next --save

@EdDevs2503 I tried yours but it didn't work for me. I found out that when I tried to import { useRouter, matchPath } from 'next/router', the `matchPath` is undefined. I'm not sure what will be the equivalent of `matchPath` in next.

**Comment by kami23** [comment]
Hello , i have the same problem and the version of react that i am using is : 
    "react": "^16.9.0",
    "react-dom": "^16.9.0", 
How to solve this ? i tried to use the next solution and it didn't work

**Comment by kapilgorve** [comment]
@kami23 I just ran into this error. It could also be an indication that you are importing something in your component which doesn't exist. 
For me it was this - import { withNavigation } from '@react-navigation/web';
This `withNavigation` doesn't exist inside the `@react-navigation/web` .

**Comment by codecrimson** [comment]
I was getting the same error. It was due to importing useState from the wrong library. If you're using >16.8 make sure you have:

`import React, { useState } from 'react';`

**Comment by N-Akoma** [comment]
TypeError: Cannot read property 'pxToRem' of undefined
(anonymous function)
C:/Users/Young Akoma/Desktop/Anthony/page-app/src/Components/Explore.js:16
  13 |   width: '100%',
  14 | },
  15 | heading: {
> 16 |   fontSize: theme.typography.pxToRem(15),
     | ^  17 |   flexBasis: '33.33%',
  18 |   flexShrink: 0,
  19 | },

please i really need help for this. i cant resolve it

**Comment by kevinjose1** [comment]
I got the same error, but somehow sorted it well . The issue was due to the React and React- Dom versions. I was using the older versions of React and React-dom. The issue sorted when i upgraded into latest version. 
Please make sure that you update both React and React-dom at the same time.
Run the below commands in cmd to upgrade React . Open your package.json and check your current react and react-dom before updating.

npm install --save react@latest
npm install --save react-dom@latest

**Comment by jith87** [comment]
> Hey, your problem is complicated, but i could resolvet. You problem is React version. run this command: npm install react@next react-dom@next --save

This fixed the issue.

**Comment by waqaramjad** [comment]
> @sagar-gavhane you got a few glitches in your project setup.
> /src/components/Input/input.js
> 
> Line 1 should be
> import Input from './Input.jsx'
> 
> /src/screens/auth/Login/Login.jsx
> Line 1 should be
> import Input from '../../../components/Input/input.js'
> 
> and in package.json
> use
> "react": "next",
> "react-dom": "next",
> 
> You should be good after that.

thanks @nikilok  you resolved my issue but i want to know the logic behind that because i never used next in react version

**Comment by N-Akoma** [comment]
thanks

**Comment by zackster** [comment]
I had to upgrade `react-redux`, delete my `node_modules`, then reinstall.

**Comment by danielravina** [comment]
I was struggling with this for the past 2 hours. was a typo for me
```
import React, { useContex } from "react";`

... many lines below ...

const { projects } = useContex(AppContext);
```

😭

**Comment by wjes** [comment]
My error was trying to import `useQuery` from `react` instead of `@apollo/react-hooks`, thanks you all!

**Comment by jeremy-hunter** [comment]
Wow - thank you - I did the same thing 🤦

**Comment by code-dreamer-broker** [comment]
npm install ng2-charts@2.2.0 --save          work  for me. fine

**Comment by mediamaker** [comment]
I was using a named export instead of default and had to remove the brackets
`import { useSiteMetadata }  from "../hooks/useSiteMetadata"`
`import  useSiteMetadata  from "../hooks/useSiteMetadata"`

**Comment by dandv** [comment]
All these comments about how tiny typos caused all this time waste and frustration, suggest that this error could be clarified by echoing the incorrect name. @gaearon, anything that could be done in that direction, or is this a JavaScript limitation?

**Comment by atidivya** [comment]
I am still getting the error "TypeError: Object(...) is not a function" for using the useParams from react.

    "react": "^16.13.1",
    "react-dom": "^16.13.1",

**Comment by jyotiprakash111** [comment]
@atidivya Do you able to solve the issue or not ?

**Comment by KrunalRajkotiya** [comment]
I had come across the same problem and what worked for me is updating the **react** and **react-dom** to the **latest version**. 

**To update to the latest version.**
`npm install --save react@latest`
`npm install --save react-dom@latest`

**Comment by THPubs** [comment]
> I was using a named export instead of default and had to remove the brackets
> `import { useSiteMetadata } from "../hooks/useSiteMetadata"`
> `import useSiteMetadata from "../hooks/useSiteMetadata"`

Thanks a lot @mediamaker . This worked for my use case where I was importing a function which use React inside a NextJS project.

**Comment by lavahasif** [comment]
npm install --save react@latest
npm install --save react-dom@latest
this solved my problem .when i was using usestate and useeffect in react

**Comment by smtlab** [comment]
Just do `npm audit fix` =)

**Comment by gaearon** [comment]
I'm going to lock this because the comments are either getting repetitive or include unrelated suggestions.

If you have this error, it means you're importing something that doesn't exist. It doesn't have to do with React per se.
