### ISSUE TITLE
useEffect causes 'callback is not a function' exception

### ISSUE THREAD

**Issue by kristiandupont** [facebook/react#15647]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

`useEffect` results in the following exception in the console:
```
Uncaught TypeError: callback is not a function
    at flushFirstCallback (scheduler.development.js:348)
    at flushWork (scheduler.development.js:441)
    at MessagePort.channel.port1.onmessage (scheduler.development.js:188)
```

I am unable to isolate the problem enough to create a sandbox that reproduces it. I am posting it here in case there is still some value in it (it seems slightly related to https://github.com/react-navigation/react-navigation/issues/5851, https://github.com/gaearon/overreacted.io/issues/460 and even https://github.com/facebook/react/issues/15194).
This is my component:
```js
const RemoteControlledSliderRaw = ({ activeIndex, currentlyDragging, className, children }) => {
	const [forcedX, setForcedX] = React.useState(null);

	React.useEffect(() => {
		if (currentlyDragging) {
			window._animateItem.update = setForcedX;
		} else {
			if (window._animateItem.update) {
				setForcedX(null);
				window._animateItem.update = null;
			}
		}
	}, [currentlyDragging]);

	return (
		<div>
			<SliderCore activeIndex={activeIndex} forcedX={forcedX} className={className}>
				{children}
			</SliderCore>
		</div>
	);
};
```

What *might* be interesting is that I set a global object to point to a `setState` setter. That can be called from the outside. I am not sure exactly how the exception occurs, but if I comment out the entire `useEffect` bit, it goes away.

**What is the expected behavior?**
No exception. Or at least one that provides some explanation as to what is wrong.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.6. I don't know if this worked with earlier versions.

**Comment by liamm12** [comment]
Same problem
I'm playing with React Hooks for more than a few hours, I'm probably ran into an intriguing problem: using setInterval just doesn’t work as I'd expect with react-native

    function Counter() {
      const [time, setTime] = useState(0);
      useEffect(() => {
        const id = setInterval(() => {
          console.log('called');
          setTime(time + 1);
        }, 1000);
        return () => {
          console.log('cleared');
          clearInterval(id);
        };
      }, [time]);

      return <div>{time}</div>;
    }

The code above should clearInterval every time that `time` state changes
It works fine on `ReactJS` but on `React-native` I'm getting an error says `"Callback() it's not a function"`

[enter image description here][1]

It's working as expected in Reactjs

https://codesandbox.io/s/z69z66kjyx


  [1]: https://i.stack.imgur.com/E4yMV.png

    "dependencies": {
        "react": "16.8.3",
        "react-native": "^0.59.6",
        ...}

**Comment by gaearon** [comment]
I've seen this happen because of wrong `scheduler` version. Unfortunately RN didn't have explicit dependency on `scheduler` version (by mistake).

If you see this, try adding `"scheduler": "0.14.0"` dependency into your project (or, if that breaks your project, try the opposite — `"scheduler": "0.13.6"`).

**Comment by liamm12** [comment]
Hey @gaearon I have fixed the problem by using `useLayoutEffect` instead of `useEffect` it works fine :)

**Comment by gaearon** [comment]
That’s not a real fix and will likely blow up later. I recommend to fix the underlying problem instead.

**Comment by liamm12** [comment]
I have installed the new version of React which automaticlly installed `"scheduler": "^0.13.6"` but I'm still getting the error
<img width="676" alt="Screen Shot 2019-05-14 at 21 05 35" src="https://user-images.githubusercontent.com/33762501/57725588-cfc87d00-768d-11e9-9738-5b2cdace650a.png">
How can I update the scheduler to `0.14.0`

**Comment by gaearon** [comment]
Try adding `"scheduler": "0.14.0"` to your `package.json` and re-running your package manager.

**Comment by liamm12** [comment]
Thank you @gaearon, the bug has been fixed, I just did `npm install scheduler@0.14.0 --save-dev`

**Comment by sedenardi** [comment]
@gaearon Adding that dep didn't fix the issue for me. It seems to crop up when performing an async task in `useEffect`:

```js
const [envs, setEnvs] = useState(null);
useEffect(() => {
  const load = async function() {
    const res = await getAllEnvs();
    setEnvs(res);
  };
  load();
}, []);
```
Am I doing something wrong?

**Comment by snettah** [comment]
Not work for me with [react-konva](https://github.com/konvajs/react-konva).
I try both 0.14 and 0.13.6

**Comment by ejbp** [comment]
I'm having the same error here with `scheduler: "^0.14.0"` when using `withStyles` or `makeStyles`  from `material-ui ("@material-ui/styles": "^4.1.2")`.

I'm using `"webpack": "^4.35.0"`

**Comment by Yaolegol** [comment]
Walking around that issue I finded solution:
1. this problem occurs when there are multiple versions of scheduler in the project,
2. for check this use `npm list scheduler`, or `yarn why scheduler` (more info [here](https://github.com/facebook/react/issues/16364))
3. if you have several versions of scheduler check link above or
- use with npm [this](https://github.com/rogeriochaves/npm-force-resolutions)
- use with yarn like this:
```
"resolutions": {
    "scheduler": "0.15.0"
  }
```
4. in any case after each manipulation with scheduler **ALWAYS reload you react app** (e.g. npm start)

**Comment by jmayergit** [comment]
> @gaearon Adding that dep didn't fix the issue for me. It seems to crop up when performing an async task in `useEffect`:
> 
> ```js
> const EnvironmentSelectorScreen = function() {
>   const [envs, setEnvs] = useState(null);
>   useEffect(() => {
>     const load = async function() {
>       const res = await getAllEnvs();
>       setEnvs(res);
>     };
>     load();
>   }, []);
> 
>   if (!envs) {
>     return (<Loading />);
>   }
> 
>   return (
>     <View style={style.container}>
>       <FlatList
>         data={envs}
>         renderItem={({ item }) => <Env item={item} />}
>       />
>     </View>
>   );
> };
> ```
> 
> I can try to make an example repo later today that reproduces the issue.

It could be a syntactic error. Like you I am performing an async task is useEffect. This stack overflow post solved my issue which oddly enough was a missing semi-colon

https://stackoverflow.com/questions/42036349/uncaught-typeerror-intermediate-value-is-not-a-function

before
`  React.useEffect(() => {
      const data = someFunction()
      (async () => {
      })()
  }, [...])`

add a semi colon after someFunction

after
`  React.useEffect(() => {
      const data = someFunction();
      (async () => {
      })()
  }, [...])`

**Comment by Adecodess** [comment]
> Thank you @gaearon, the bug has been fixed, I just did `npm install scheduler@0.14.0 --save`

i am having this issue, i am using yarn and installed sheduler version 0.20.2 but the error still persist

**Comment by Sid2202** [comment]
I am having the same issue. I am using npm to install all my packages and everything worked fine, until I included useEffect.

```javascript
import { useState, useEffect, useCallback } from "react"
``` 

This is how I have imported useEffect from react. BTW, I am using Next.js here.

```javascript
const getAllData = useCallback( async() => {
        await axios.post('http://localhost:5080/api/table', data)
            .then((response) => {
                setTable(response.data)
            })
    })

useEffect=(() => {
        getAllData();
    },[getAllData])

``` 
Here is how I have used in useEffect and useCallback in my functions. I am trying to map data that is stored in the table useState
```javascript
<tbody>
                        {
                            table?.map(({_id,name,email,contact,hobby})=>(
                                <tr key={_id}>
                                    <td>{_id}</td>
                                    <td>{name}</td>
                                    <td>{email}</td>
                                    <td>{contact}</td>
                                    <td>{hobby}</td>
                                </tr>
                            ))
                        }                    
</tbody>
``` 

The script actually worked fine when I had not used useEffect and was just calling the function through a button.
Please let me know if I have done something wrong here.

**Comment by kemisstep** [comment]
> I am having the same issue. I am using npm to install all my packages and everything worked fine, until I included useEffect.
> 
> ```js
> import { useState, useEffect, useCallback } from "react"
> ```
> 
> This is how I have imported useEffect from react. BTW, I am using Next.js here.
> 
> ```js
> const getAllData = useCallback( async() => {
>         await axios.post('http://localhost:5080/api/table', data)
>             .then((response) => {
>                 setTable(response.data)
>             })
>     })
> 
> useEffect=(() => {
>         getAllData();
>     },[getAllData])
> ```
> 
> Here is how I have used in useEffect and useCallback in my functions. I am trying to map data that is stored in the table useState
> 
> ```js
> <tbody>
>                         {
>                             table?.map(({_id,name,email,contact,hobby})=>(
>                                 <tr key={_id}>
>                                     <td>{_id}</td>
>                                     <td>{name}</td>
>                                     <td>{email}</td>
>                                     <td>{contact}</td>
>                                     <td>{hobby}</td>
>                                 </tr>
>                             ))
>                         }                    
> </tbody>
> ```
> 
> The script actually worked fine when I had not used useEffect and was just calling the function through a button. Please let me know if I have done something wrong here.

+1
