### ISSUE TITLE
Can't install react-test-renderer@16.10.2 because of scheduler@^0.16.2 dependency

### ISSUE THREAD

**Issue by arolonger** [facebook/react#17018]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Can't install react-test-renderer in latest version (16.10.2)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
1. run npm i react-test-renderer --save-dev
2. get No matching version found for scheduler@^0.16.2 error

**What is the expected behavior?**
react-test-renderer is installed

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Not connected with React version

**Comment by threepointone** [comment]
Cc @acdlite

**Comment by briankellydev** [comment]
+1. running npm view scheduler shows the latest version is @0.15.0- react-dom is trying to install @0.16.2 which shows on the npm page but doesn't seem to be propagating down.

**Comment by threepointone** [comment]
Odd, because `npm view scheduler` shows the latest version as 0.16.2 to me. Is this still an issue for you folks? 
![image](https://user-images.githubusercontent.com/18808/66305904-fd081700-e91d-11e9-93e4-9c1f230cb589.png)

**Comment by briankellydev** [comment]
It appears to be working now, it may have just been broken for a few hours for some reason, or maybe someone fixed it quietly. Thank you!

**Comment by threepointone** [comment]
Stupid caches :) I’m glad it’s fixed now! Closing.

**Comment by vickylance** [comment]
@threepointone @briankellydev  I am still facing this issue not on my local machine though but its failing with the above error message in Jenkins build
