### ISSUE TITLE
DevTools can't inspect object without prototype

### ISSUE THREAD

**Issue by yume-chan** [facebook/react#17754]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

1. Select a component
2. The right panel (property panel?) always shows `Loading...` 
3. The following error is printed to the console.

```
backend.js:1 Uncaught TypeError: Cannot read property 'name' of undefined
    at O (backend.js:1)
    at s (backend.js:1)
    at s (backend.js:1)
    at l (backend.js:1)
    at Object.inspectElement (backend.js:6)
    at t.<anonymous> (backend.js:6)
    at t.r.emit (backend.js:6)
    at backend.js:32
    at t (backend.js:8)
```

![image](https://user-images.githubusercontent.com/1330321/71661150-497dba00-2d88-11ea-8df1-235f24ba793f.png)

I don't know why you minify the output, but the call stack points to here:

https://github.com/facebook/react/blob/f887d1aa27336baa0bc292158793a5a244c712b6/packages/react-devtools-shared/src/utils.js#L391

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/falling-wave-1j0qe

**What is the expected behavior?**

React DevTools displays the props of the selected component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.12.0
Chrome 79.0.3945.88
IDK

**Comment by bvaughn** [comment]
Thanks for the repro case.

**Comment by bvaughn** [comment]
FYI this issue should be fixed in v4.4 (released today)

**Comment by PatNeedham** [comment]
What is the release process like? I still see 4.3.0 on the Chrome web store: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
![image](https://user-images.githubusercontent.com/967811/71840238-e2634c80-308a-11ea-9504-c0f562670823.png)

**Comment by bvaughn** [comment]
The release process is...the newer version will go live once Chrome reviews it. They seem to have fallen pretty far behind around the hoildays.
