### ISSUE TITLE
[DevTools] Component inspector not loading for large components

### ISSUE THREAD

**Issue by katz12** [facebook/react#17813]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**
The component inspector works fine on most components, but on ones that are particularly large with many large props it is stuck on "Loading...".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
You should be able to reproduce the issue on: https://data.world/jonloyens/an-intro-to-dataworld-dataset

Navigate to the component with the key: "jonloyens/an-intro-to-dataworld-dataset". Other components above and below that one will load, but that one specifically will not.

**What is the expected behavior?**
It should load the component tree eventually. Previous to the 4.3.0 update these components loaded fine.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Our app uses React version 16.8.3.
I am on dev tools version 4.3.0 on Chrome 79.0.3945.88 on MacOS Catalina 10.15.2 (but others on earlier versions of MacOS are having the same issue).

I have a suspicion that this may be related to https://github.com/facebook/react/pull/17579 as this change has made a big impact on our app (mostly in a good way). We use ImmutableJS, and that change has made it much easier to navigate Immutable props since it preloads the values. The component that is loading slowly uses a proportionately large number of Immutable props to other components.

**Comment by lunaruan** [comment]
Hey! Thanks for the repro steps. I've tried it with the latest version of the extension and it looks like the bug no longer happens. I think that's because it was fixed in #17233, but that version has not yet deployed to your browser. Fortunately that version went live in the Chrome store yesterday evening, so it should deploy to you soon! 
I'm going to close this issue since it's been fixed on our end. If you're still able to reproduce it with version 4.4.0 please let us know and we'll reopen the issue. 
cc: @bvaughn

**Comment by crisscrosskao** [comment]
I'm actually still having this bug on version 4.4.0. It works for me in Chrome, but not for me in Electron. 

![Screenshot from 2020-01-28 11-17-26](https://user-images.githubusercontent.com/5176026/73297113-d1a48300-41bf-11ea-9d98-84711b90973c.png)
![Screenshot from 2020-01-28 11-16-54](https://user-images.githubusercontent.com/5176026/73297114-d23d1980-41bf-11ea-8ab2-28d8d9d7c98e.png)

**Comment by bvaughn** [comment]
@crisscrosskao Going to need a repro.
