### ISSUE TITLE
Bug: Devtools' update-notifier usage is overly eager

### ISSUE THREAD

**Issue by NickHeiner** [facebook/react#20061]
When I run the devtools, I get the `update-notifier` message:

```
   ╭────────────────────────────────────────╮
   │                                        │
   │    Update available 4.4.0 → 4.9.0      │
   │   Run npm i react-devtools to update   │
   │                                        │
   ╰────────────────────────────────────────╯
```

I appreciate the goal of this message. However, the suggested command to run is incorrect for my repo. We use yarn, not npm. And we use a monorepo. This is confusing for devs who are new to the repo.

Would it be possible to suppress the `update-notifier` message? The team that manages usage of react-devtools in our tool chain is happy to stay on top of updates themselves.

**Comment by bvaughn** [comment]
This message is not something `react-devtools` logs. Pretty sure this is just something the `npm` command does to let you know that you aren't running the latest minor/bugfix version within your current major.

**Comment by recurx** [comment]
Hey @NickHeiner ! If you have not started, can I give it a try? Seems pretty straight-forward to add the check.

**Comment by bvaughn** [comment]
I don't think anyone has started on this, so please feel free @recurx.

**Comment by recurx** [comment]
Thanks @bvaughn . `updateCheckInterval` by default is 1 day. Changing this to 7 days. Should I also change the message to just this: 
<img width="310" alt="Screenshot 2020-10-21 at 7 31 09 PM" src="https://user-images.githubusercontent.com/71846122/96730607-fc7cda00-13d3-11eb-9336-d6e6cf50bed4.png">

**Comment by bvaughn** [comment]
I think the message is fine. Any reason to change it?

**Comment by recurx** [comment]
Was just wondering about this sentence in the issue - 

> "However, the suggested command to run is incorrect for my repo. We use yarn, not npm. And we use a monorepo. This is confusing for devs who are new to the repo."

**Comment by bvaughn** [comment]
I see.

We could add update the wording to include `yarn` too I guess. Not sure we should try to cover all possible use cases (like monorepos). The main purpose of this message is to notify people that an update is available, but I think the added action of "run npm i react-devtools" is a nice prompt.

**Comment by recurx** [comment]
The 'how to install' is a nice prompt. But there would be many different ways people would be using `react-devtools`. For example if I'm using it globally, I'll have to add a `-g`, yarn users would need to do `yarn add react-devtools` . We can do something like this:
<img width="463" alt="Screenshot 2020-10-21 at 8 20 57 PM" src="https://user-images.githubusercontent.com/71846122/96737126-f0e0e180-13da-11eb-9093-1ea1237c5d61.png">
There might be more use-cases. Let me know what you think.

**Comment by bvaughn** [comment]
Like I said, I don't think we need to cover all use case :smile: It's nice to mention the most common case or two. That looks fine.

**Comment by NickHeiner** [comment]
Yes, @recurx, thanks for pointing out my concern about the message being incorrect. :smile: Changing the message interval doesn't really address the reason I opened this issue.

I agree that it's impractical to cover all use cases. And, frankly, for my users, it's not great to have a message that says something like "use yarn or use npm", because devs in my repo **must** use yarn. 

The ideal solution from my end (and one that should be very easy to implement) is simply to provide an option to suppress showing this update notifier entirely. That option could default to `false`, and most people wouldn't need to know it existed.

**Comment by gaearon** [comment]
> it's not great to have a message that says something like "use yarn or use npm", because devs in my repo must use yarn.

Practically speaking, developers in your repo will encounter many libraries that say `npm i something` in their instructions. So they need to be aware anyway that `npm i something` should be substituted by `yarn add something` in general in your repo. I don't think this is a critical issue in this case.

**Comment by NickHeiner** [comment]
I know that many packages use update-notifier, but in this case, we actually don't have a ton of other command line tools printing out install instruction messages. 

And, while I agree that in general, JS devs should have the wherewithal to translate `npm` commands to `yarn` commands, this monorepo is contributed to by generalist devs who are not as familiar with the JS ecosystem, and I'm trying to keep things as clean as possible for them.

Is this entire issue critical? No, probably not in any scenario. As a monorepo infrastructure maintainers, would I prefer to have more control over which messages are shown to my dev community? Absolutely. :smile:

**Comment by bvaughn** [comment]
> Changing the message interval doesn't really address the reason I opened this issue.

While it's not the outcome you're advocating for, I think it is still relevant to what prompted you to open the issue– since it reduces how frequently you'll see this (non-actionable) prompt.

If you would like to submit a PR that adds the ability to permanently opt out of this, you'd be welcome to. It doesn't look like that's something the library we're using provides support for though– and I suspect it's an uncommon enough want that not many people would be interested in doing the leg work but maybe I'm wrong.

**Comment by NickHeiner** [comment]
Yes, I agree that reducing the frequency reduces the impact of the issue. :smile:

Perhaps I will submit that PR! Thanks for the invitation.

**Comment by minshinkhant** [comment]
Hi, is this issue still opened?

**Comment by shaiguelman** [comment]
Hi, if possible I would like to tackle this issue. Please let me know if it is still available. Thanks!

**Comment by NickHeiner** [comment]
I will hold off to give the other commenters a chance to work on this.

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Hi, is this issue still open for contribution, I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!

**Comment by Fuckmylimpdick** [comment]
Fuck it

**Comment by gabrielsanttana** [comment]
Like @bvaughn said, it would be cool to mention the two most common cases, which in this case would be for `npm` and `yarn`.

**Comment by ad99526** [comment]
Hi, is this issue still open for contribution as I intend to work on this?

**Comment by CobyCoding** [comment]
I believe this issue has been fixed. Can we close this issue, please?

**Comment by rakesh456** [comment]
Is this issue fixed?

**Comment by mynameisankit** [comment]
Is the issue still unresolved or fixed? I would like to work on this

**Comment by bvaughn** [comment]
I'm going to close this issue because I think the current state of this feature is fine and I have no plans to change it. If someone would like to submit a PR+proposal for a new behavior though, I will review it.
