### ISSUE TITLE
Error: "Cannot add node "1" because a node with that id is already in the Store."

### ISSUE THREAD

**Issue by dharapx** [facebook/react#21436]
### Which website or app were you using when the bug happened?

Please provide a link to the URL of the website (if it is public), a CodeSandbox (https://codesandbox.io/s/new) example that reproduces the bug, or a project on GitHub that we can checkout and run locally.

### What were you doing on the website or app when the bug happened?

If possible, please describe how to reproduce this bug on the website or app mentioned above:
1. 
2. 
3. 

### Generated information

DevTools version: 4.13.1-93782cfed2

Call stack:
(none)

Component stack:
(none)

GitHub URL search query:
https://api.github.com/search/issues?q=Cannot%20add%20node%20%20because%20a%20node%20with%20that%20id%20is%20already%20in%20the%20Store.%20in%3Atitle%20is%3Aissue%20is%3Aopen%20is%3Apublic%20label%3A%22Component%3A%20Developer%20Tools%22%20repo%3Afacebook%2Freact

**Comment by bvaughn** [comment]
@dharapx Sorry you hit this problem

Unfortunately though, it doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by ZackeryBayle** [comment]
Project: https://github.com/ZackeryBayle/TrollyReactJS 
Back end: https://github.com/ZackeryBayle/TrollyCRM

While working on the project doing some code splitting.

`
Update existing issue:
Error: "Cannot add node "1" because a node with that id is already in the Store."
Uncaught Error: Cannot add node "1" because a node with that id is already in the Store.`
I am pretty new so please forgive the crazy mess you are about to witness.

**Comment by bvaughn** [comment]
Hey @ZackeryBayle! This is a great help.

> While working on the project doing some code splitting.

Can you elaborate a little more on what I'd need to do to reproduce the error myself beyond running these two projects locally?

**Comment by ZackeryBayle** [comment]
@bvaughn - I was working on just rendering some props on the home screen after splitting my form code into its own component.
On render throws error
Page still renders

I hope that helps, let me know if there is anything else I can provide.

**Comment by ZackeryBayle** [comment]
I have simply removed everything from the rendering page (home.js) and the error still happens. The only thing being rendered is my navBar and footer. Nothing has changed on these components for weeks. I haven't done any updates to dependence. 


![image](https://user-images.githubusercontent.com/8448004/117327908-f61def00-ae47-11eb-91e1-6e67aa064a5d.png)

**Comment by bvaughn** [comment]
Oh that's excellent. Can you push a branch and point me at it so I can check it out and repro?

I got stuck having to install mongodb this morning to run the backend and then I had meetings.

**Comment by ZackeryBayle** [comment]
Here is the new branch  `https://github.com/ZackeryBayle/TrollyReactJS/tree/staging-issues`

**Comment by bvaughn** [comment]
Thanks!

**Comment by bvaughn** [comment]
@ZackeryBayle So you just load the page and see the error?

I can't repro that. (Now that Mongo is installed.)

**Comment by ZackeryBayle** [comment]
correct Just loading the page produces that error. Nothing about the mongo should any effect on this atm because all the components have been removed from the  pages/home.js 

I don't know what a component filter is sorry I'm really new at this. This is actually my capstone project for bootcamp.

**Comment by bvaughn** [comment]
Ah ok that's interesting. I wonder why I'm not able to reproduce the bug using the same branch/app.

Any chance you'd be up for a quick Zoom call tomorrow to look at it together? No problem if you're not, but if you are– shoot me an email (brian.david.vaughn at gmail) or a DM on twitter (@ brian_d_vaughn)

**Comment by bvaughn** [comment]
Thank you for the update, @ZackeryBayle

**Comment by ZackeryBayle** [comment]
Okay all components are loaded back in and rendering... no more error. I'm at a loss on this one. 

Only thing I can say is I was trying to figure out how to raise state so I could update a a parent state from a child when this happened. Let me know if there is anything else I can do to provide any more info or help.

**Comment by bvaughn** [comment]
@yrambler2001 Need a repro case. Can you share one?

**Comment by bvaughn** [comment]
Understood. If you're able to narrow it down, even to something that happens once and a while, repro steps would be helpful.

**Comment by eps1lon** [comment]
Repro: https://github.com/eps1lon/react-devtools-repro-no-matching-node/tree/main
React devtools version: 4.13.2 (e468072e17)
Steps included in repro.

https://user-images.githubusercontent.com/12292047/117544707-e6a6cd80-b022-11eb-9f8f-bb8cfd9f7743.mp4

**Comment by bvaughn** [comment]
Thanks for the repro, @eps1lon!

My first guess is that this has to do with Fast Refresh and force-remounting. I'll have to dig in.

**Comment by bvaughn** [comment]
I _think_ I've captured the bug in a unit test:
https://github.com/bvaughn/react/blob/d49ba6b598522e4a5c0d93e215d7e3c7c51fef2c/packages/react-devtools-shared/src/__tests__/FastRefreshDevToolsIntegration-test.js#L164-L254

**Comment by bvaughn** [comment]
I'm not sure of the best way to handle this. DevTools can read the `_debugNeedsRemount` field during unmount to detect what's happened, but at this point– how does it get from id 4 back to id 1? I think I'd have to add a lot of metadata tracking to be able to map from type-to-id.

I think the best approach might be to add a hook to React to inform DevTools of when a forced clone+remount has happened.

**Comment by bvaughn** [comment]
This test captures the bug:
```js
withErrorsOrWarningsIgnored(["Expected warning during render"], () => {
  render(`
      const {useState} = React;

      export default function Component() {
        const [state, setState] = useState(1);

        console.warn("Expected warning during render");

        return <div />;
      }
    `);
});
expect(store).toMatchInlineSnapshot(`
      ✕ 0, ⚠ 1
      [root]
          <Component> ⚠
    `);

let element = container.firstChild;

withErrorsOrWarningsIgnored(["Expected warning during render"], () => {
  patch(`
      const {useState} = React;

      export default function Component() {
        const [state, setState] = useState(1);

        console.warn("Expected warning during render");

        return <div id="one" />;
      }
    `);
});
expect(store).toMatchInlineSnapshot(`
      ✕ 0, ⚠ 2
      [root]
          <Component> ⚠
    `);

// State is preserved; this verifies that Fast Refresh is wired up.
expect(container.firstChild).toBe(element);
element = container.firstChild;

withErrorsOrWarningsIgnored(["Expected warning during render"], () => {
  patch(`
      const {useEffect, useState} = React;

      export default function Component() {
        const [state, setState] = useState(3);
        useEffect(() => {});

        console.warn("Expected warning during render");

        return <div id="one" />;
      }
    `);
});
expect(store).toMatchInlineSnapshot(`
      ✕ 0, ⚠ 3
      [root]
          <Component> ⚠
          <Component> ⚠
    `);
```

In the third snapshot, there should not be a duplicate `<Component>`.

**Comment by bvaughn** [comment]
I _think_ #21506 might be one way to fix this issue.

**Comment by bvaughn** [comment]
To anyone above who can reproduce this bug but _can't share source code_ – would you be interested in trying a build of DevTools (I can attach to this issue) to see if I've fixed the problem with some changes I've made locally?

**Comment by bvaughn** [comment]
@eps1lon, @ZackeryBayle Would either of you be willing to try this build and let me know if it fixes your issue?

[ReactDevTools.zip](https://github.com/facebook/react/files/6502363/ReactDevTools.zip)

**Comment by bvaughn** [comment]
#21516 _might_ fix this problem but without a repro I can't be sure. I'm going to close this issue for now though and we can re-open (with a repro) if that's not the case.

**Comment by eps1lon** [comment]
> @eps1lon, @ZackeryBayle Would either of you be willing to try this build and let me know if it fixes your issue?
> 
> [ReactDevTools.zip](https://github.com/facebook/react/files/6502363/ReactDevTools.zip)

@bvaughn I can still reproduce my repro (https://github.com/facebook/react/issues/21436#issuecomment-835406075) with 
 the devtools version in your zip (4.13.2-723f44a088).

**Comment by bvaughn** [comment]
That's so interesting. I tested a variation of your repro (without the error logged _inside the effect_). My change fixes that repro in the browser, or both cases in a unit test, but...sure enough, I can see the error you're referring to in the Store now too :(

My bad! Let me dig further.

**Comment by bvaughn** [comment]
I see a difference, but I'm not sure I understand it. Based on logging...

```js
// DevTools mounts Component version X with ID 5
mountFiberRecursively() Component (5) 
recordMount() Component (5) 
recordResetChildren() Component (5) 

// DevTools untracks Component version X (...)
untrackFiberID() Component (5) 

// DevTools sees an error logged for Component version X+1 in an effect and generates a new ID 6 for it
getOrGenerateFiberID() Component (6) Generated a new UID
onErrorOrWarning Component (6)  error: "effect"

// DevTools sees an error logged for Component version X+1 during render and generates a new ID 7 for it
getOrGenerateFiberID() 2:Component (7) Generated a new UID
onErrorOrWarning 2:Component (7)  warn: "render"

// DevTools sees an error logged for Component version X+1 with ID 6 (but it should be unmounting version X with ID 5)
recordUnmount() Component (6)  
```

**Comment by bvaughn** [comment]
@eps1lon Can you try this build? 😬

[ReactDevTools.zip](https://github.com/facebook/react/files/6503746/ReactDevTools.zip)

**Comment by bvaughn** [comment]
Should be fixed by #21523.

If you'd like to verify, download this build:
[ReactDevTools.zip](https://github.com/facebook/react/files/6505445/ReactDevTools.zip)

And follow these steps to install it:
https://user-images.githubusercontent.com/29597/118749019-b6cda600-b82a-11eb-9449-ef56f41eced5.mp4

**Comment by eps1lon** [comment]
> @eps1lon Can you try this build? 😬
> 
> [ReactDevTools.zip](https://github.com/facebook/react/files/6505445/ReactDevTools.zip)

Still the same issue with DevTools version 4.13.3-0f72f7361f, Chrome Version 90.0.4430.212 (Official Build) (64-bit) on Windows 10 and react-dom 17.0.2. 

Let me check if this also reproduces on Linux.

**Comment by bvaughn** [comment]
@eps1lon Wait, you still see this with the repro above? Are you sure you're running the latest unpacked extension? I'm able to repro it 100% of the time without the fix and 0% with the fix.

Maybe we could VC and look at it together if you're still reproing?
