### ISSUE TITLE
Error: "Cannot remove node "2626" because no matching node was found in the Store."

### ISSUE THREAD

**Issue by neerajverma101** [facebook/react#21442]
### Which website or app were you using when the bug happened?

Please provide a link to the URL of the website (if it is public), a CodeSandbox (https://codesandbox.io/s/new) example that reproduces the bug, or a project on GitHub that we can checkout and run locally.

### What were you doing on the website or app when the bug happened?

If possible, please describe how to reproduce this bug on the website or app mentioned above:
1. 
2. 
3. 

### Generated information

DevTools version: 4.13.1-93782cfed2

Call stack:
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21499:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19607:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19767:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37788:39)

Component stack:
(none)

GitHub URL search query:
https://api.github.com/search/issues?q=Cannot%20remove%20node%20%20because%20no%20matching%20node%20was%20found%20in%20the%20Store.%20in%3Atitle%20is%3Aissue%20is%3Aopen%20is%3Apublic%20label%3A%22Component%3A%20Developer%20Tools%22%20repo%3Afacebook%2Freact

**Comment by bvaughn** [comment]
Hi @neerajverma101!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by JakeGinnivan** [comment]
FWIW I just got this error and clicked on the link in dev tools to this issue. HMR got a 500 loading the new module from Vite, then renders failed. This happened when i saved a file I was editing with invalid syntax so it couldn't be transformed.

**Comment by bvaughn** [comment]
@JakeGinnivan Are you able to reliably reproduce this? (If so, can you share an example file before/after so I can try as well?)

**Comment by mastorm** [comment]
Funnily, i also run into this issue. I am running vite, just like @JakeGinnivan

**Comment by bvaughn** [comment]
@mastorm Repro?

**Comment by gaearon** [comment]
I wonder if it has something to do with Fast Refresh's restore mechanism where it remounts previously failed roots. Maybe those don't get registered somehow?

**Comment by neerajverma101** [comment]
I'm working on a project based on nextjs and when trying to locate a component through the extension it is getting crashed.

![Screenshot from 2021-05-11 12-16-02](https://user-images.githubusercontent.com/13080807/117770608-c0677480-b252-11eb-93d4-dce2eb982050.png)

**Comment by Ostefanini** [comment]
Hello, quick fix for users here: on firefox I've rollbacked to version 4.13.0.
Go to about:addons and remove the extension.
Then click here: https://addons.mozilla.org/firefox/downloads/file/3767928/react_developer_tools-4.13.0-fx.xpi
(it's the direct link to install a specific version from this page: https://addons.mozilla.org/fr/firefox/addon/react-devtools/versions/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org )

Add the extension and enjoy debugging again !

**Comment by bvaughn** [comment]
@Ostefanini @neerajverma101 @mastorm @JakeGinnivan A repro for this bug would be hugely helpful. So far we've gotten reports but no steps to reproduce it (so we can fix it).

Temporarily rolling back the extension is fine to work around the immediate problem but it's not a long term solution 😄

**Comment by pauldewilson** [comment]
Also getting this error on a project I've been working on for two months without issue. I'd like to offer up the repo but it's private with sensitive info. If there's anything I can do to help that isn't divulging the repo then I'm happy to do so. Sorry I can't be of more help, but this is very much a problem for me so keen to help where I can. Thanks.

<img width="961" alt="Screenshot 2021-05-11 182450" src="https://user-images.githubusercontent.com/61115269/117858905-43ee8900-b286-11eb-9558-da106ad24d09.png">

**Comment by bvaughn** [comment]
Unfortunately we really just need a repro. The stack trace is going ot be the same, so screenshots of the error don't give us any additional information. :) Thanks though.

**Comment by pauldewilson** [comment]
> That would be super helpful

I'm sorry, tried and failed (sort of). Too much of the project depends upon connections that must remain private. FWIW, trying to trim the fat somehow solved the problem. I removed some connections to a Parse server hosted on back4app, and also removed a google maps JS API. Specifically, I get this problem with material UI dialog onClose after opening a dialog on a @react-google-maps/api map. Oddly, it also occurs when navigating away from one of my navbar pages which requires a connection to said B4A server but not other pages that don't. Sorry I can't be of more help.

**Comment by minimalknave127** [comment]
I fixed this issue with **hard reload** (ctrl +f5) in chrome

**Comment by amabelleS** [comment]
I also run into this issue, working with react. Its not my repo to share.. so unfortunately I cant. But I got very strange behavior with the state, trying to update after fetching data from the server, it does not reach the state, most of the times... it does when I update the code on VSC on the first render after the save, but then when I refresh the page the data disappears from the state. I added a button, saving mock data in the state ({name: me}), got an additional layer of strangeness.

**Comment by bvaughn** [comment]
I _think_ #21506 might be one way to fix this issue.

**Comment by bvaughn** [comment]
@pauldewilson Would you be interested in trying a build of DevTools (that I can attach to this issue) to see if I've fixed the problem with some changes I've made locally?

**Comment by pauldewilson** [comment]
> @pauldewilson Would you be interested in trying a build of DevTools (that I can attach to this issue) to see if I've fixed the problem with some changes I've made locally?

Hi @bvaughn yes very happy to try that. Thank you!

**Comment by bvaughn** [comment]
@pauldewilson Thank you! Here's a build that fixes the problem for me (in unit tests and my local repro).

[ReactDevTools.zip](https://github.com/facebook/react/files/6498247/ReactDevTools.zip)

**Comment by pauldewilson** [comment]
> @pauldewilson Thank you! Here's a build that fixes the problem for me (in unit tests and my local repro).
> 
> [ReactDevTools.zip](https://github.com/facebook/react/files/6498247/ReactDevTools.zip)

Thanks, tried but still getting the error I'm afraid.
<img width="642" alt="error" src="https://user-images.githubusercontent.com/61115269/118643686-cae6b880-b7d4-11eb-949f-ca99ae883c74.png">

**Comment by bvaughn** [comment]
Bummer. :( What happens if you dismiss the error dialog?

**Comment by bvaughn** [comment]
Thanks for trying it, @pauldewilson. I'm curious, what happens if you dismiss the error dialog?

I guess at this point, I'd really like to get my hands on a repro from you. I could sign an NDA or something if that would be helpful?

**Comment by bvaughn** [comment]
This issue is now blocked by not having a repro. #21516 should _improve_ the situation but apparently not fix it entirely. That being said, I'm not sure how to proceed until I get a repro from someone, so I'm tagging all of the folks above who have commented that they're seeing this in hopes that one of them can share something with me.

**Comment by bvaughn** [comment]
@pauldewilson Can you try this build? 😬

[ReactDevTools.zip](https://github.com/facebook/react/files/6503746/ReactDevTools.zip)

**Comment by pauldewilson** [comment]
> @pauldewilson Can you try this build? 😬
> 
> [ReactDevTools.zip](https://github.com/facebook/react/files/6503757/ReactDevTools.zip)

Seems to have fixed it! Thank you! And no NDA required after all!

**Comment by bvaughn** [comment]
Thanks for confirming

**Comment by bvaughn** [comment]
Should be fixed by #21523.

If you'd like to verify, download this build:
[ReactDevTools.zip](https://github.com/facebook/react/files/6505445/ReactDevTools.zip)

And follow these steps to install it:
https://user-images.githubusercontent.com/29597/118749019-b6cda600-b82a-11eb-9449-ef56f41eced5.mp4

**Comment by jcubic** [comment]
I still have this error, on CodeSandbox, when I switch routes.

https://codesandbox.io/s/react-router-remote-table-demo-ojn3wp?file=/src/hooks.ts
