### ISSUE TITLE
[DevTools Bug] Cannot add node "476" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by Bodyhealer** [facebook/react#21636]
### Website or app

https://zhivika.ru/product/26406103_plastyr_perc_bperf_10smh18sm_n

### Repro steps

1. Load page.
2. Open react components.
3. Click button "Смотреть все аптеки" for unfold all list.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.5-0ae5290b54

### Error message (automated)

Cannot add node "476" because a node with that id is already in the Store.

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment]
Hi @Bodyhealer. I'm no table to reproduce the error following the steps you've described.

https://user-images.githubusercontent.com/29597/121020334-47ced780-c76e-11eb-8004-093dddedea3b.mp4

Any suggstion?

**Comment by rdcavanha** [comment]
I've got this error today as well on Firefox 89.
Adding to OP's report, this happens when refreshing the page while the dev console is open with the `Components` tab shown:
![image](https://user-images.githubusercontent.com/15946186/121795165-8cca9200-cbe4-11eb-9f71-972ae97ee0b7.png)

**Comment by bvaughn** [comment]
@rdcavanha You're seeing this bug using OP's codebase? Or a different app?

**Comment by rdcavanha** [comment]
> @rdcavanha You're seeing this bug using OP's codebase? Or a different app?

Completely different app.

**Comment by bvaughn** [comment]
@rdcavanha Could you share your code then? I'm still looking for a repro of this issue that I can trigger.

**Comment by rdcavanha** [comment]
@bvaughn Sorry, I can't share the code as it is a private repo.

However, I've noticed that after I refreshed my Firefox profile the issue seems to be gone. I've tried using the React extension on the same app as before and was unable to reproduce the bug again.

This leads me to believe that it's probably some sort of conflict with another extension (just a guess). Unfortunately I can't say which one exactly as I no longer have all the extensions installed due to the profile refresh. The fact that this has very low occurrence seems to support this idea of extension conflict as well.

**Comment by bvaughn** [comment]
Thanks for the extra info.

**Comment by Romej** [comment]
[Win10 64-bit] [Firefox 89.0]
Got the issue today, you may be able to replicate it with the following steps : 
1. If the React dev tools extension is installed, uninstall it
2. Go on a web page that uses React and open the Firefox dev tools
3. In a new/different tab, install the React dev tools extension
4. Keep the Firefox devtools opened and refresh your page (CTRL + F5)
5. Go to the Components tab

**Comment by dgattey** [comment]
macOS 11.3.1 Macbook Pro M1, Firefox 89.0.1.

1. I installed React devtools for the first time ever on Firefox on this computer
2. Navigated to my localhost site that was already running before extension install
3. Refreshed the page with cmd-R with DevTools open and Caching disabled in Firefox DevTools settings
4. Observe `Uncaught Error: Cannot add node "1" because a node with that id is already in the Store.` on every single page reload. Also occurs on every single page navigation, but I get `Uncaught Error: Cannot remove node "310" because no matching node was found in the Store.` instead, where the node id changes every time. With the first error, I get node "1" every time.

**Comment by bvaughn** [comment]
Unfortunately errors after the extension is first installed or removed might be something that we can't do much about.

**Comment by dgattey** [comment]
Reloading the whole browser did work, but tab / console refresh didn't work @bvaughn. Thanks!

**Comment by sj-rai** [comment]
I faced this issue when I had two devtools frontend open, one in the browser extension and a devtools standalone, closing one stopped giving this error. Maybe that's what is causing this.

**Comment by IjtihadIslamEmon** [comment]
The image file is missing

**Comment by lunaruan** [comment]
I'm able to periodically reproduce this bug, so I can take a look!

**Comment by perqa** [comment]
Just reproduced in Chrome using standalone react-devtools simultaneously with the browser extension. Even though the steps to reproduce might not be the same as the original reporter, as well as being misuse of the extension, I hope they might giva a clue to the root cause.

`Uncaught Error: Cannot add node "1" because a node with that id is already in the Store.`

**Prerequisites:**

1. Installed standalone React devtools (Electron app)
2. React app prepared for profiling with standalone React devtools (Electron app)

**Steps to reproduce:**

1. Activate React devtools profiler in Chrome
2. Reload page in Chrome
3. Start standalone React devtools (Electron app)
4. Reload page in Chrome and see error message

**Comment by millikr2** [comment]
@rdcavanha I'm using Chrome and got the same error. It went away when I changed one of my classNames, I'm guessing one of my extensions was using the same className.

**Comment by noahehall** [comment]
getting the same error

![image](https://user-images.githubusercontent.com/10324554/133134106-938f10b4-f5ea-49a2-b712-6130b18d3993.png)

[reproducable commit](https://github.com/noahehall/nodeproto/tree/6aace3eed2d316e19506488a55094ee9db005480)

steps to reproduce

- pulldown branch (see link above)
-  `$ cd packages/tests`
- `$ pnpm install`
- `$ pnpm start:react`

open firefox developer edition

**Comment by bvaughn** [comment]
@noahehall The install step fails for me:
```
jsync: command not found
```
I don't know what `jsync` is but I tried installing it via the instructions [here](https://metacpan.org/pod/JSYNC) and I still get the error.

Looks like the error is coming from `packages/tools/jsync`

**Comment by noahehall** [comment]
@bvaughn sorry about that - jsync is internal to the repo (/root/packages/tools/jsync)

give me a second to do a fresh clone and determine exactly what needs to be done to run the app

**Comment by noahehall** [comment]
@bvaughn  hah!

Upraded node to 16.9.1 and recieved the same error as you.

the the real issue was a preinstall script inside jsync/package.json (ment to automatically sync root pkgjsons to child pkjsons)

This has been fixed and you should be able to follow the steps and reproduce without issue

**Comment by bvaughn** [comment]
@noahehall Am I checking the `update-wtf` branch for the repro now? HEAD of that branch still fails for me:
```
$ pnpm install
...
../.. postinstall$ cp node_modules/@nodeproto/configproto/.flowconfig .
│ cp: node_modules/@nodeproto/configproto/.flowconfig: No such file or directory
└─ Failed in 39ms
 ELIFECYCLE  Command failed with exit code 1.

**Comment by noahehall** [comment]
the branch extract-nodeproto-utica

**Comment by noahehall** [comment]
there's a pkjson script that copies the flowconfig , you should comment it

**Comment by bvaughn** [comment]
There is no `extract-nodeproto-utica` branch. Please double check your repro and get back to me, @noahehall. Maybe you forgot to push?

**Comment by bvaughn** [comment]
```
$ pnpm start:react
 WARN  Unsupported engine: wanted: {"node":">=16.5"} (current: {"node":"v14.17.0","pnpm":"6.15.0"})

> @nodeproto/tests@0.0.0 start:react /Users/bvaughn/Downloads/nodeproto/packages/tests
> concurrently pnpm:start:webpack:server pnpm:start:reactdevtools

[start:reactdevtools]  WARN  Unsupported engine: wanted: {"node":">=16.5"} (current: {"node":"v14.17.0","pnpm":"6.15.0"})
[start:reactdevtools]
[start:reactdevtools] > @nodeproto/tests@0.0.0 start:reactdevtools /Users/bvaughn/Downloads/nodeproto/packages/tests
[start:reactdevtools] > react-devtools
[start:reactdevtools]
[start:webpack:server]  WARN  Unsupported engine: wanted: {"node":">=16.5"} (current: {"node":"v14.17.0","pnpm":"6.15.0"})
[start:webpack:server]
[start:webpack:server] > @nodeproto/tests@0.0.0 start:webpack:server /Users/bvaughn/Downloads/nodeproto/packages/tests
[start:webpack:server] > node integration/configproto/webpack.server.mjs
[start:webpack:server]
[start:webpack:server] file:///Users/bvaughn/Downloads/nodeproto/packages/libraries/configproto/src/webpack/bff/server.webpack.mjs:37
[start:webpack:server]   const controller = new AbortController();
[start:webpack:server]                      ^
[start:webpack:server]
[start:webpack:server] ReferenceError: AbortController is not defined
[start:webpack:server]     at webpackServer (file:///Users/bvaughn/Downloads/nodeproto/packages/libraries/configproto/src/webpack/bff/server.webpack.mjs:37:22)
[start:webpack:server]     at file:///Users/bvaughn/Downloads/nodeproto/packages/tests/integration/configproto/webpack.server.mjs:10:20
[start:webpack:server]     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
[start:webpack:server]     at async Loader.import (internal/modules/esm/loader.js:177:24)
[start:webpack:server]     at async Object.loadESM (internal/process/esm_loader.js:68:5)
[start:webpack:server]  ELIFECYCLE  Command failed with exit code 1.
[start:webpack:server] pnpm run start:webpack:server exited with code 1
```

**Comment by noahehall** [comment]
@bvaughn you need to update your node version to 16.5 > greater

**Comment by bvaughn** [comment]
There's still no `extract-nodeproto-utica` branch, @noahehall.

I'm running out of steam on this repro case. Can you please  double check that you've pushed the branch you think you've pushed, and tell me exactly which branch/revision to checkout and which commands I need to run in order to repro this?

**Comment by noahehall** [comment]
extract-nodeproto-utils

**Comment by bvaughn** [comment]
> @bvaughn you need to update your node version to >= 16.5

Still seeing the error above:
```
$ node -v
v16.9.1

$ pnpm start:react
 WARN  Unsupported engine: wanted: {"node":">=16.5"} (current: {"node":"v14.17.0","pnpm":"6.15.0"})

> @nodeproto/tests@0.0.0 start:react /Users/bvaughn/Downloads/nodeproto/packages/tests
> concurrently pnpm:start:webpack:server pnpm:start:reactdevtools

[start:reactdevtools]  WARN  Unsupported engine: wanted: {"node":">=16.5"} (current: {"node":"v14.17.0","pnpm":"6.15.0"})
[start:reactdevtools]
[start:reactdevtools] > @nodeproto/tests@0.0.0 start:reactdevtools /Users/bvaughn/Downloads/nodeproto/packages/tests
[start:reactdevtools] > react-devtools
[start:reactdevtools]
[start:webpack:server]  WARN  Unsupported engine: wanted: {"node":">=16.5"} (current: {"node":"v14.17.0","pnpm":"6.15.0"})
[start:webpack:server]
[start:webpack:server] > @nodeproto/tests@0.0.0 start:webpack:server /Users/bvaughn/Downloads/nodeproto/packages/tests
[start:webpack:server] > node integration/configproto/webpack.server.mjs
[start:webpack:server]
[start:webpack:server] internal/process/esm_loader.js:74
[start:webpack:server]     internalBinding('errors').triggerUncaughtException(
[start:webpack:server]                               ^
[start:webpack:server]
[start:webpack:server] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/bvaughn/Downloads/nodeproto/packages/libraries/envproto/node_modules/@nodeproto/wtf/src/fsproto.mjs' imported from /Users/bvaughn/Downloads/nodeproto/packages/libraries/envproto/src/ssl.mjs
[start:webpack:server]     at finalizeResolution (internal/modules/esm/resolve.js:276:11)
[start:webpack:server]     at moduleResolve (internal/modules/esm/resolve.js:699:10)
[start:webpack:server]     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
[start:webpack:server]     at Loader.resolve (internal/modules/esm/loader.js:88:40)
[start:webpack:server]     at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
[start:webpack:server]     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
[start:webpack:server]     at link (internal/modules/esm/module_job.js:55:36) {
[start:webpack:server]   code: 'ERR_MODULE_NOT_FOUND'
[start:webpack:server] }
[start:webpack:server]  ELIFECYCLE  Command failed with exit code 1.
[start:webpack:server] pnpm run start:webpack:server exited with code 1
```

And there's no webserver running on localhost:8080 after running `pnpm start:react`.

**Comment by noahehall** [comment]
@bvaughn your patience is emmy-award winning. 

I was able to resolve this issue internally (thus for other users facing this issue, its likely a configuration problem)

so what exactly was the issue? shit if i know... but the [develop branch](https://github.com/noahehall/nodeproto/tree/develop) works both:

- running react@alpha + reactdevtools directly
- running react@alpha + reactdevtools behind an haproxy gateway



working on the problem you were facing running my nodeproto framework, I ended up

- enabling the new node corepack API 
- removing NVM and using `pnpm env` to install node 
- deleting the fkn pnpm cache and starting fresh (this is where the discrepenancy between my env and yours was borne)
- **writing a bunch of tests... ** which led to some **tweaking** of my webpack, swc, babel, and esbuild configurations 



![image](https://user-images.githubusercontent.com/10324554/134832756-d036ee55-d455-499f-9650-38f08c17ebb5.png)

**Comment by bvaughn** [comment]
Thank you for the update, @noahehall 👍🏼 I'm glad you were able to get the issue resolved on your end.

We'll keep this issue open for others in case more repros pop up in the future 😄

**Comment by virajtk** [comment]
> ### Website or app
> https://zhivika.ru/product/26406103_plastyr_perc_bperf_10smh18sm_n
> 
> ### Repro steps
> 1. Load page.
> 2. Open react components.
> 3. Click button "Смотреть все аптеки" for unfold all list.
> 
> ### How often does this bug happen?
> Every time
> 
> ### DevTools package (automated)
> react-devtools-extensions
> 
> ### DevTools version (automated)
> 4.13.5-0ae5290b54
> 
> ### Error message (automated)
> Cannot add node "476" because a node with that id is already in the Store.
> 
> ### Error call stack (automated)
> _No response_
> 
> ### Error component stack (automated)
> _No response_
> 
> ### GitHub query string (automated)
> ```
> https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
> ```

I got the same issue, then I relaized I have the same extention dulicated, I used Edge and I installed both React Dev Tool extensions for both chrom and edge. After I disabled / remove the Chrome extention ( because I used Edge browser ). The issue was gone.

**Comment by bvaughn** [comment]
Thank you for the extra information @virajtk

**Comment by macbury** [comment]
Same problem here :(

**Comment by jstejada** [comment]
Merging #22570 into this issue, which seems to be another instance of this issue.

**Comment by Delice0** [comment]
Just produced today. 
![image](https://user-images.githubusercontent.com/59118341/145873992-67ac277e-25e0-401b-a541-b843740e3bf6.png)

**Comment by bvaughn** [comment]
@Delice0 I'm sorry to hear you're seeing this.

Unfortunately without instructions on how to repro, this isn't particularly useful for tracking down and fixing the issue.

**Comment by KonstantinZhukovskij** [comment]
The same issue with the last RN and node 16.13.1

**Comment by bvaughn** [comment]
Please take a moment to read other comments above (like https://github.com/facebook/react/issues/21636#issuecomment-992792710) before adding an addition one, folks.

@KonstantinZhukovskij Without any repro instructions, "same issue" doesn't really give us any way to help.

**Comment by AllanChain** [comment]
With React Native bug reproduction: https://github.com/AllanChain/rn-dev-bug

Steps:

- Connect phone and computer to the same LAN
- `yarn install`
- `yarn start`
- Launch globally installed `react-devtools` standalone (`v4.22.1`)
- Open project in Expo Go
- Refresh by pressing <kbd>r</kbd> in terminal

"Cannot add node" error will appear, roughly once in three refreshes.

**Comment by Bodyhealer** [comment]
Maybe this bug gone. For now I'm using v4.22.0-0229baee2

**Comment by bvaughn** [comment]
Here is another repro: https://github.com/facebook/react/issues/23035#issuecomment-1010676425

Thanks @junkboy0315!

**Comment by bvaughn** [comment]
Possible fixed by #23156.

**Comment by Bablu-singh** [comment]
I am not able to use the elements tab in React Native Devtools
<img width="1389" alt="Screenshot 2022-01-23 at 3 48 06 PM" src="https://user-images.githubusercontent.com/22193849/150674041-c375fea2-4673-44c4-96b9-03d0d88cd4ae.png">

**Comment by bvaughn** [comment]
Closing this issue since we're releasing a new version today (with the fix from #23156).

**Comment by troZee** [comment]
> Here is another repro: [#23035 (comment)](https://github.com/facebook/react/issues/23035#issuecomment-1010676425)
> 
> Thanks @junkboy0315!
> 
> I realized that upgrading react-devtools-core >= 4.22.0 breaks react-native-debugger.
> 
> [Minimal reproductive sample (zip)](https://github.com/facebook/react/files/7852149/sample.zip)
> 
> This sample works fine with debugger at first. (it uses react-devtools-core v4.21.0) But it will break if you follow the steps below.
> 
> * remove `react-devtools-core` in `yarn.lock`. <- v4.21.0 will be removed
> * run `yarn add react-devtools-core`.    <- v4.22.1 will be installed
> * run expo, and then, you can see that devtools is broken.

Thank you @bvaughn. Based on working example I was able to fix DevTool in Expo 44. I was following this [article](https://blog.expo.dev/developing-react-native-with-expo-and-flipper-8c426bdf995a) but it did not work out on my end.
