### ISSUE TITLE
Generate XML compatible markup

### ISSUE THREAD

**Issue by zpao** [facebook/react#2278]
Take the alternative approach discussed in #2161. I think we can take advantage of the self-closing information we already have in ReactDOM (and make use of in ReactDOMComponent).

cc @audreyt in case you're interested in taking a stab at this.

**Comment by Acubed** [comment]
I made a pull request to fix the self-closing tags and boolean attributes. This still leaves some features to be implemented, including:

* XML Namespaces (required for stand-alone documents and valid Polyglot HTML)
* the "raw text" elements: `script` and `style` tags
* xml:lang attributes
* Comments containing the sequence `--`
* Extra whitespace added to some HTML elements (pre, textarea, etc)

The definitive reference on how to generate markup that parses the same in both of HTML5's parsing modes is [Polyglot Markup: A robust profile of the HTML5 vocabulary](http://www.w3.org/TR/html-polyglot/). In the long run, being able to generate non-HTML vocabularies would be nice: stand-alone SVG documents, DocBook, Atom, etc.

**Comment by dcousens** [comment]
What was the status of this as of React 0.14?

**Comment by jimfb** [comment]
My understanding is that this issue was fixed in https://github.com/facebook/react/pull/2842 and this issue can be closed.

@dcousens My understanding is that this works in 0.14; let us know if you run into any issues.

**Comment by Acubed** [comment]
That patch mostly makes the page _not break_ when parsing HTML in XML mode. It's still not suitable for arbitrary XML, like SVG, Atom, DocBook, OpenDocument, or the huge variety of domain-specific vocabularies out there.

React is just describing a DOM document or fragment; and text/html, XML, EXI, and even a certain subset of HAML and Jade, are all serializations of a DOM document. Right now React is limited to describing the subset that can also be rendered in text/html, but there's no design limitation on supporting others.

All DOM elements have an xmlns, e.g. in my console right now, I get:

    > document.firstElementChild.namespaceURI
    < "http://www.w3.org/1999/xhtml"

Adding support for elements with arbitrary namespaces is all that you really need. e.g.:

    var svgns = 'http://www.w3.org/2000/svg';
    React.createElement(svgns, 'svg', {}, [])

If rendered in XML mode, this would output:

    <svg xmlns="http://www.w3.org/2000/svg"/>

If adding `xmlns=` to every element every time the namespace changes becomes too repetitive, there's standard ways to declare or calculate a namespace prefix.

**Comment by kevinSuttle** [comment]
Any updates on this?

**Comment by spicyj** [comment]
No, sorry. React DOM is primarily designed for HTML.

**Comment by gaearon** [comment]
Closing as it's unlikely we'll be working on this.
