### ISSUE TITLE
Update documentation on `initializeTouchEvents`, removing tap-delay

### ISSUE THREAD

**Issue by jefffriesen** [facebook/react#2468]
The documentation on `React.initializeTouchEvents(true)` could use a little love:
http://facebook.github.io/react/docs/events.html#touch-events

I realize it's currently changing and may be removed (#436, #1170). Is it still required? Is it only required if we use react-tap-event-plugin?

What's most confusing about it is when to use it. Use it if the page being rendered will ever render on a touch device? Or do we detect touch using something like `Modernir.touch` and then set it to true?

Related to this issue is the tap delay. Maybe suggest in the documentation using a plugin like tap-event-plugin? 

I would submit a PR but really don't know what the documentation should say. Thanks!

**Comment by mschipperheyn** [comment]
+1

**Comment by OscarGodson** [comment]
Yeah, it makes it sound that it will actually use touch events which is does not.

**Comment by levitanong** [comment]
+1. At the moment, as of React 0.12 on my project, touch events still trigger on touch devices with or without initializeTouchEvents.

**Comment by malissa** [comment]
I'm also curious what this would be used for.  I'm loading my react app in a ios simulator and things seem ok without explicitly setting initializeTouchEvents to true.  To be fair I haven't tried on an actual device.

**Comment by chicoxyzzy** [comment]
`initializeTouchEvents` was removed in #3442

**Comment by chicoxyzzy** [comment]
BTW docs sources are fixed https://github.com/facebook/react/pull/3442/files#diff-8949552676e903f486caef00b60d5630L144

**Comment by iamstarkov** [comment]
@chicoxyzzy @jefffriesen I still see [note about `initializeTouchEvents`][docs]. is it an error?

> To enable touch events, call `React.initializeTouchEvents(true)` before rendering any component.

[docs]: http://facebook.github.io/react/docs/events.html#touch-events

**Comment by chicoxyzzy** [comment]
@iamstarkov looks like the version with fixes is not shipped yet
