### ISSUE TITLE
Bug: Stale values returned from useOptimistic when state changes

### ISSUE THREAD

**Issue by dorshinar** [facebook/react#27617]
The `optimisticState` returned from `useOptimistic` is stale when the `state` param passed to `useOptimistic` is changed. The change could come from an RSC reponse or from a `setState`. 

React version: 18.2.0

## Steps To Reproduce

1. Call `useOptimistic` with a `state` variable
2. Update the value of `state` either via `setState` or any other method that would cause a rerender
3. The initial `state` is returned as the `optimisticState` 
![image](https://github.com/facebook/react/assets/17943918/84759716-79e1-47f0-b237-b8d68b89014b)

Link to code example: https://github.com/dorshinar/next-optimistic-bug

I've recreated the bug in a Next project, but the important component is this:

```tsx
export function Form() {
  const [arrFromServer, setArrFromServer] = useState([1, 2, 3]);

  useEffect(() => {
    const interval = setInterval(() => {
      setArrFromServer((a) => [...a, a.length + 1]);
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  const [optimisticArr] = useOptimistic(arrFromServer, (s) => s);
  console.log("🚀 ~ arrFromServer:", arrFromServer);
  console.log("🚀 ~ optimisticArr:", optimisticArr);

  return <div>{JSON.stringify(optimisticArr)}</div>;
}
```

## The current behavior
When there is no form submission in progress, the `optimisticArr` always returns the initial `state` provided to it. 

## The expected behavior
I'd exepct that `optimisticState` returned from `useOptimistic` to be in sync with the `state` param passed to it.

**Comment by magoz** [comment]
I'm experiencing the same issue.

**Comment by Feel-ix-343** [comment]
Me too. Downgrading to next 13 solves it for now

**Comment by ipv6sq** [comment]
same issue here.

**Comment by JovanJevtic** [comment]
Same

**Comment by Elee-Lawleit** [comment]
same here, for me it sometimes flashes the correct value before changing back to the original value

**Comment by JovanJevtic** [comment]
Same here. It's not more experimental version, why is this happening?

**Comment by JovanJevtic** [comment]
> same here, for me it sometimes flashes the correct value before changing back to the original value

For me it does every time

**Comment by JovanJevtic** [comment]
https://github.com/facebook/react/assets/62719173/25ea9058-27fa-4367-bde8-3686f7d89c26

`
'use client'

import { addTodo } from "@/actions/todo";
import { Todo } from "@prisma/client";
import { ElementRef, useOptimistic, useRef } from "react";
import { v4 as uuid } from 'uuid'
import AddButton from "./AddButton";

type Props = {
    todos: Todo[]
}

const Form = ({ todos }: Props) => {

    const formRef = useRef<ElementRef<'form'>>(null)

    const [optimisticTodos, addOptimisticTodo] = useOptimistic<Todo[], string>(
        todos,
        (currTodos, newTodo: string) => {
            return [
                {
                    text: newTodo,
                    id: uuid(),
                    createdAt: new Date(Date.now()),
                    updatedAt: new Date(Date.now())
                },
                ...currTodos
            ]
        }  
    )

    return(
        <>
            <form
                ref={formRef}
                action={async formData => {
                    formRef.current?.reset();

                    addOptimisticTodo(formData.get("text") as string)

                    await addTodo(formData)
                }}
                className="flex-row flex"
            >
                <label>Input text</label>
                <input 
                    type="text"
                    name="text"
                    className="bg-blue-950"
                />
                <AddButton />
            </form>
            <ul className="mt-5">
                {
                    optimisticTodos.map(todo => (
                        <li key={todo.id} className="mb-3">
                        <p>{todo.text}</p>
                        </li>
                    ))
                }
            </ul>
        </>
    );
}

export default Form
`

**Comment by tom-sherman** [comment]
> When there is no form submission in progress, the optimisticArr always returns the initial state provided to it.

I think this is an expected behaviour of useOptimistic. Or rather, the optimistic update is replaced with the new state as soon as the transition is over. When there is no async work in the transition, the optimistic update is replaced instantly.

**Comment by acdlite** [comment]
This is, indeed, a bug — I apologize for not looking into this until now (thanks @tom-sherman for the ping on ~Twitter~ X). I remember getting the ping from @sophiebits but forgot to follow up.

Should be fixed by https://github.com/facebook/react/pull/27936

**Comment by acdlite** [comment]
The fix has now landed in the most recent React and Next.js canaries. Thanks for the bug report!

**Comment by dattran1232003** [comment]
@acdlite Hi, can I ask when this will be released? I'm using React `^18.3.1` and Next `^14.2.5` but I still have the problem.

**Comment by CodingReaper1** [comment]
nothing is fixed 
![image](https://github.com/user-attachments/assets/8f2a3284-d7b1-45cc-ac8c-bb3b26eebce7)
these are my packages
![image](https://github.com/user-attachments/assets/cb37145b-f965-4b6c-aaa9-ba0f0a53638b)
i tried react 18.3.1 didnt work
i tried without action with start transition didnt work 
it appears and dissapears in 0.3 sec or something 
am i doing something obvious very wrong?
