### ISSUE TITLE
[DevTools Bug]: stuck at loading react element tree

### ISSUE THREAD

**Issue by Arichy** [facebook/react#31135]
### Website or app

N/A

### Repro steps

1. It's my local react app.
2. added `<script src="http://localhost:8097"></script>` at the beginning of `head` tag in `index.html`
3. run `react-devtools` in terminal

<img width="800" alt="image" src="https://github.com/user-attachments/assets/b6eb23f7-8036-4c61-983d-ce2bf858f704">

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Thanks for reporting this. This has been fixed in https://github.com/facebook/react/pull/31102 and will be out with 6.0.1 soon

**Comment by Ario99** [comment]
I started this issue yesterday. It's still persistent despite following the troubleshooting instruction to cycle toggle the react dev tools plugin. Allowing file links didn't help either.

**Comment by limitedmage** [comment]
I am seeing the same issue too @hoxyq on version 6.1.5
