### ISSUE TITLE
[React 19] dangerouslySetInnerHTML causes repaint

### ISSUE THREAD

**Issue by lukahartwig** [facebook/react#31660]
## Summary

Given the following component

```jsx
function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      <button onClick={() => setCount((count) => count + 1)}>{count}</button>
      <div dangerouslySetInnerHTML={{ __html: "I should only paint once" }} />
    </>
  );
}
```

Clicking the button should not trigger a repaint of "I should only paint once". This works as expected in react@18.3.1 but not in react@19.0.0-rc.1 or react@0.0.0-experimental-5b0ef217-20241202.

* Browser: Chrome Version 131.0.6778.86 (Official Build) (arm64)
* OS: MacOS 15.1.1 (24B91)

## react@18.3.1

https://github.com/user-attachments/assets/3912ae19-f0b5-4425-abd4-0c376d9f8bb7

## react@0.0.0-experimental-5b0ef217-20241202

https://github.com/user-attachments/assets/d486783d-819a-40fe-a9f8-8c537009e173

[Source Code](https://github.com/lukahartwig/react-dangerouslysetinnerhtml)

**Comment by agriffis** [comment]
I suspect this is the same root cause as https://github.com/facebook/react/issues/31600

**Comment by lukahartwig** [comment]
Yes, this looks like the same issue.

Basically, the regression is React used to check if the passed html string has changed before applying it, but in the above mentioned refactor that was replaced by a [generic equality check](https://github.com/facebook/react/blob/c56c6234328a29930487295afe61597db48f058c/packages/react-dom-bindings/src/client/ReactDOMComponent.js#L1860).

But because `setDangerouslyInnerHTML` takes an object, the equality check always fails and React always overrides `el.innerHTML`.

**Comment by SANGET** [comment]
This usage fix the issue for my case:

```jsx
<div
  contentEditable={true}
  dangerouslySetInnerHTML={useMemo(
    () => ({ __html: value }),
    [value]
  )}
/>
```

**Comment by agriffis** [comment]
bump

**Comment by sim51** [comment]
Same issue here, and the fix from @SANGET works.
But it's a work around IMHO.

**Comment by cuonghuunguyen** [comment]
We have the same issue!

**Comment by floppydisken** [comment]
Experienced same issue, but wasn't a problem in previous versions. Fixed by using the useMemo solution.

**Comment by Revya7** [comment]
Same issue, also fixed by using the useMemo solution.

**Comment by joggS1** [comment]
Same issue!

**Comment by KilleRBBC** [comment]
We also had this issue when upgrading to React 19, also fixed by the useMemo solution.
A bit concerned that this level of regression was allowed into the React 19 release.

**Comment by juliebarwick** [comment]
+1 on having the same issue. Grateful for the useMemo suggestion - worked for us too.

**Comment by serhalp** [comment]
I guess I was too slow here, but this is still occurring.

This was a problematic undocumented behavioural change I encountered when upgrading Gatsby to support React 19. I dealt with it, but at the very least it should be documented in the React 19 release notes.
