### ISSUE TITLE
Context warning refers to missing Gist

### ISSUE THREAD

**Issue by dandelany** [facebook/react#3880]
I'm getting a few warnings like "Warning: owner-based and parent-based contexts differ... (see: http://fb.me/react-context-by-parent)"

However, http://fb.me/react-context-by-parent seems to refer to a Gist which no longer exists. Has it moved?

**Comment by zpao** [comment]
Bah, this is because @jimfb changed his username and I guess GitHub doesn't set up redirects for everything.

Last time I looked we couldn't update fb.me links but I'll look again. It wasn't too much of a problem before but I'll force the issue this time.

**Comment by dandelany** [comment]
Thanks @zpao . For posterity/until then, looks like the referenced Gist is https://gist.github.com/jimfb/0eb6e61f300a8c1b2ce7

**Comment by jimfb** [comment]
Another option is that I can change my username back to jsfb (at least temporarily until fbme is fixed).  Just let me know.

**Comment by ZeikJT** [comment]
Still 404, 18 days later

**Comment by jimfb** [comment]
@zpao What action do we want to take here?

**Comment by zpao** [comment]
Fixed.

**Comment by ZeikJT** [comment]
Still broken for me, going to http://fb.me/react-context-by-parent leads to https://gist.github.com/jsfb/0eb6e61f300a8c1b2ce7 which shows me a `Whoops` page

**Comment by zpao** [comment]
Maybe your browser cached the redirect? This is working for me.

```
~% curl -I http://fb.me/react-context-by-parent
HTTP/1.1 301 Moved Permanently
Location: https://gist.github.com/jimfb/0eb6e61f300a8c1b2ce7
Vary: Accept-Encoding
Content-Type: text/html
X-FB-Debug: Y4MZfizL4TEgxAHIZW/5Ggh2/D4jn7rTB3COZu37DYRkvy6+ZE0pD2IkIMOWFCS2hbYNWByE5UWWnjff9a661g==
Date: Mon, 01 Jun 2015 18:11:08 GMT
Connection: keep-alive
Content-Length: 0
```

**Comment by ZeikJT** [comment]
Didn't realize it had sent back as a 301.
Makes sense that it would cache that.
