### ISSUE TITLE
React.TestUtils.Simulate.click on React's label element

### ISSUE THREAD

**Issue by Kureev** [facebook/react#4322]
Dear all,

I've faced an issue about testing collaboration between label and checkbox elements.

#### Context:
I have a custom checkbox with label:
![image](https://cloud.githubusercontent.com/assets/2273613/8599001/3ca2f6d2-265e-11e5-9e02-6db5ae8d04b6.png)

My goal is to test few behaviors, and one of them is "Component should fire `onChange` when user click on title". Title in our case is "Create link hotspots...". So in browser everything is fine, but when I started cover it by tests I faced that click emulation on label doesn't lead to change checkbox's value *immediately*, but works if I hack it with `setTimeout(..., 0)`.

#### My testing stack:
```
├── babel@5.6.14
├── chai@3.0.0
├── chai-spies@0.6.0
├── jsdom@0.3.4
├── mocha@2.2.5
├── react@0.13.3
```

#### Question:
Why it happens and do you have any plans to improve this behavior?

**Comment by jimfb** [comment]
In reading your problem description, nothing jumps out at me.  Do you have a simple jest test that we can run in our repository to reproduce the bug?

As a side note: TestUtils is mostly internal API, intended for us to be able to test React code.  Just be aware that it isn't stable external API, and isn't technically supported.

**Comment by Kureev** [comment]
I'll do my best to provide you Jest example asap, but even now I can't assert it'll happens using Jest, because I'm **not** using it. As you can see above, it's about `mocha` + `jsdom`. 

About TestUtils - I think now everybody who do unit testing for their React components use TestUtils, not sure it's so "internal".

**Comment by jimfb** [comment]
Actually, you are correct, they are documented: https://facebook.github.io/react/docs/test-utils.html

Yeah, if we can reproduce the bug, that'll be the first step towards a fix.  Thanks!

**Comment by nikolaymatrosov** [comment]
It seems this behavior is related to jsdom bug, that was fixed in [jsdom@4.3.0](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#430).
But that version works only with io.js.
Can you try run your tests with **the latest jsdom** to figure out if it is jsdom bug?

**Comment by Kureev** [comment]
Yeah, seems it's related to jsdom. Damn, what a stupid decision to support only `io.js`

**Comment by Kureev** [comment]
Hm, I was wrong: I've tried to replace `node` and `jsdom v3` by `iojs` and `jsdom v5` and the issue is still there. I'll make a simple test case as I promised

**Comment by jimfb** [comment]
Ping @Kureev for a simple testcase.

**Comment by Kureev** [comment]
I think it can be closed now (slightly outdated)
