### ISSUE TITLE
IE11 block change events if disabled

### ISSUE THREAD

**Issue by brigand** [facebook/react#4457]
Repro: https://jsbin.com/gebasa/3/edit?js,output

Given:

```xml
<input 
  disabled={true}
  type="checkbox"
  checked={trueOrFalse} 
  onChange={alert} 
  />
```

On at least IE11 a double click on checkbox causes onChange to be called. If it's just adding an if statement, normalizing this would be nice. It may also affect other elements/events like `<button disabled onClick={f}>`, misc screen readers, etc.

Workaround: duplicate the disabled boolean logic in the handler.

The report was from **sim1234** on IRC and verified by **phi0x**.

**Comment by zpao** [comment]
I think we already have some logic to disable this for buttons, should be doable.

**Comment by johansuperstar** [comment]
What's the status on this? Experienced the same issue today using React v.0.13.3 in IE11.

**Comment by scvnc** [comment]
I am also experiencing this disabled double-click checkbox behavior in React 0.14.3 and IE11, 10, 9. https://jsbin.com/mezujo/edit?html,js,output

**Comment by janusch** [comment]
Just a short update that this is still an issue in react 15.0.1 . So if you want to disable double clicks in IE on checkboxes a workaround is the one mentioned by @brigand above. Thank you!

**Comment by jimfb** [comment]
PRs welcomed.

**Comment by gaearon** [comment]
AFAIK this was fixed by #6215.
It should be a part of 15.0.2 (not 15.0.1, so @janusch you’ll need to update).

**Comment by hdpinto** [comment]
I'm still experiencing this issue on 15.5.4 on radio inputs. What version was this fixed on?
