### ISSUE TITLE
CSSTransitionGroup throws warnings if component is unmounted

### ISSUE THREAD

**Issue by globexdesigns** [facebook/react#4876]
Using `react-addons-css-transition-group` 0.14-rc1, I get the following errors if the component is unmounted before the animation is done. I have transitionEnterTimeout and transitionLeaveTimeout set to 300.

```
Uncaught TypeError: Cannot read property 'componentDidEnter' of undefined (ReactTransitionGroup.js:135)
> React.createClass._handleDoneEntering @ ReactTransitionGroup.js:135
> React.createClass.transition.endListener @ ReactCSSTransitionGroupChild.js:86

Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined ReactTransitionGroup.js:166
> React.createClass._handleDoneLeaving @ ReactTransitionGroup.js:166
> React.createClass.transition.endListener @ ReactCSSTransitionGroupChild.js:86
```

**Comment by mattstyles** [comment]
Yes, I have the same issue,

I know a previous fix for this sort of thing is to check if an element is mounted before using, but I dont think I can do that from the consumer end, this would have to be somewhere around https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js#L137 as the `component` (gathered from its key) will no longer exist.

**Comment by globexdesigns** [comment]
Additionally, there is also an issue if components change inside the transition group before the timeout has completed. In which case you see the following errors:

```
Cannot read property 'componentWillEnter' of undefined
    at React.createClass.performEnter (webpack:///./~/react/lib/ReactTransitionGroup.js?:126:18)
    at Array.forEach (native)
    at React.createClass.componentDidUpdate (webpack:///./~/react/lib/ReactTransitionGroup.js?:86:17)
    at CallbackQueue.assign.notifyAll (webpack:///./~/react/lib/CallbackQueue.js?:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (webpack:///./~/react/lib/ReactReconcileTransaction.js?:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (webpack:///./~/react/lib/Transaction.js?:202:25)
    at ReactReconcileTransaction.Mixin.perform (webpack:///./~/react/lib/Transaction.js?:149:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (webpack:///./~/react/lib/Transaction.js?:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (webpack:///./~/react/lib/ReactUpdates.js?:86:38)
    at Object.flushBatchedUpdates (webpack:///./~/react/lib/ReactUpdates.js?:147:19)
    at Object.ReactPerf.measure.wrapper [as flushBatchedUpdates] (webpack:///./~/react/lib/ReactPerf.js?:66:21)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (webpack:///./~/react/lib/Transaction.js?:202:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (webpack:///./~/react/lib/Transaction.js?:149:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (webpack:///./~/react/lib/ReactDefaultBatchingStrategy.js?:62:19)
    at Object.enqueueUpdate (webpack:///./~/react/lib/ReactUpdates.js?:176:22)
    at enqueueUpdate (webpack:///./~/react/lib/ReactUpdateQueue.js?:24:16)
```

The ref to the old item no longer exists by the time `performEnter` is fired and it dies trying to use an undefined component.

**Comment by iNikNik** [comment]
+1. Same issue. Exception throws after transition completes.

**Comment by spicyj** [comment]
(not sure we'll fix this for 0.14 but marking the milestone to remember to investigate)

**Comment by spicyj** [comment]
As far as I can tell, none of these are regressions in 0.14 so we'll fix them in a point release or after, not before 0.14.0. Can you post repro cases for these errors? It's difficult for anyone to look into fixing it otherwise.

**Comment by globexdesigns** [comment]
Creating an isolated, reproducible case was tricky, but here's something to get you started: 

http://jsbin.com/tojapukuxu/1/edit?html,js,output

```html
<!DOCTYPE html>
<html>
<head>
  <script src="//fb.me/react-with-addons-0.14.0-rc1.js"></script>
  <script src="//fb.me/react-dom-0.14.0-rc1.js"></script>
  <meta charset="utf-8">
  <title>JS Bin</title>
</head>
<body>
  <div id="app"></div>
</body>
</html>
```

```javascript
var ReactCSSTransitionGroup = React.addons.CSSTransitionGroup;
var render = ReactDOM.render;

var Container = React.createClass({
  getInitialState: function () {
    return {show: true};
  },

  render: function () {
    return (
      <div>
        
        <div><button onClick={this.onClick}>Click Me Quickly</button></div>
        {this.state.show ? <Issue4876 /> : null}
      </div>
     );
  },
  
  onClick: function () {
    this.setState({show: !this.state.show});
  }
})

var Issue4876 = React.createClass({
    componentDidMount () {
      this._ = setInterval(this.animate, 500)
    },
    
    componentWillUnmount () {
      clearInterval(this._);
    },
    
    getInitialState: function () {
      return {keys: [1]};
    },

    render: function () {
        return (
          <ReactCSSTransitionGroup
            transitionEnterTimeout={5000}
            transitionLeaveTimeout={5000}
            transitionName="message">
            {this.state.keys.map(function (item) {
              return <span key={item}>{item}</span>
            })}
          </ReactCSSTransitionGroup>
        );
    },
    
    animate: function () {
      this.setState({
        keys: this.state.keys.length === 1 ? [] : [1]
      })
    }
});

render(<Container />, document.getElementById('app'));
```

Spam click on the button a few times until you see the errors in the console.

**Comment by BKcore** [comment]
+1 Still happening in 0.14.
https://github.com/joe-strummer/react/commit/3d46217ca3d8888c5b1eb3edf04e37da6d265d6a fixes it for us.

**Comment by tkiethanom** [comment]
+1 @BKcore is correct, this is still happening in 0.14. 

joe-strummer@3d46217 seems to do the trick. Anticipating a merge for this soon I hope.

**Comment by spicyj** [comment]
I already said in my comment that we wouldn't fix this before 0.14. We can look at this for 0.14.1.

**Comment by patrick91** [comment]
Has this been fixed in react 0.14.2?

**Comment by spicyj** [comment]
Since it was merged after 0.1.4.2 was released, no.

**Comment by brettdorrans** [comment]
I am still seeing this exact error in 0.14.5.

`Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined
React.createClass._handleDoneLeaving @ ReactTransitionGroup.js:166
endListener @ ReactCSSTransitionGroupChild.js:86
`

**Comment by spicyj** [comment]
We fixed the issue that I knew about in 0.14.3. If you can post a small example that repros the problem we can see what else is causing this.

**Comment by brettdorrans** [comment]
It's a weird one - it seems to only happen occasionally (on some page loads, it doesn't happen, on others it happens multiple times).

Will try to create a jsfiddle to reproduce.

**Comment by pcfutures** [comment]
Still getting this in 15.4.2, any solutions?

**Comment by gaearon** [comment]
Please report any issues in https://github.com/reactjs/react-transition-group.
We are removing TransitionGroup from this repository and won’t be maintaining it here.
Sorry!
