### ISSUE TITLE
ReactTransitionGroup - Using with JQuery cause Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined

### ISSUE THREAD

**Issue by lovedota** [facebook/react#5296]
Hi
Please take a look at this https://jsfiddle.net/pvtb9jbt/
After adding some items, please click _remove_ and see the console.log

```
Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined
React.createClass._handleDoneLeaving @
```

This is cause from 

``` js
 _handleDoneLeaving: function (key) {
        var component = this.refs[key];

        if (component.componentDidLeave) { //From this line
          component.componentDidLeave();
        }
}
```

Can we check 

``` js
 if (component && component.componentDidLeave) {
    component.componentDidLeave();
 }
```

Thanks !

**Comment by andresgarza** [comment]
I'm not using jQuery but I'm also seeing this errors. Seems that `this.refs` is empty.

**Comment by spicyj** [comment]
This should have been fixed in 0.14.3.

**Comment by lovedota** [comment]
@spicyj 
I is not fixed.
Please check http://jsfiddle.net/lovedota/pvtb9jbt/

**Comment by jimfb** [comment]
Verified fiddle is using 0.14.3, appears to still throw errors.

**Comment by re6exp** [comment]
It works
http://jsfiddle.net/d7pah7dv/

**Comment by re6exp** [comment]
Doesn't work using 0.14.6
http://jsfiddle.net/d7pah7dv/

**Comment by zpao** [comment]
I think we fixed a different variant of this.

**Comment by spicyj** [comment]
@lovedota @re6exp It looks like you are hitting an error because the `done()` callback is called three times because you are animating three `td` elements. If you refactor your code to only call `done()` once, it will work better.

We should be more resilient to this behavior in ReactTransitionGroup though so that the original code you have also works.

**Comment by MichaelCereda** [comment]
I have the same issue with velocity-react (that includes velocity).

changing https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js#L185 
to

```javascript
if (component && component.componentDidLeave) {
    component.componentDidLeave();
 }
```
makes everything go smoothly, i'm going to propose a PR.
https://github.com/facebook/react/pull/6745

**Comment by matteobelfiore** [comment]
If you are using `setInterval` or `setTimeout` inside those methods to fire the `callback`, it'll be most likely one of those, still running once the Component's instance is already gone (`undefined`). I just had this issue and got rid of it replacing the intervals and timeouts with an alternative.

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
