### ISSUE TITLE
dangerouslySetInnerHTML not reconciling for P tags

### ISSUE THREAD

**Issue by Surreal9** [facebook/react#5479]
I noticed when trying to use dangerouslySetInnerHTML for a P tag in a tutorial app I am building, it was having weird behaviour when the content was being changed. I am able to get the desired behaviour by using a div or span instead. I am using React 0.14.2.

This might be similar to https://github.com/facebook/react/issues/377

To view, check out this branch:
https://github.com/Surreal9/react-tutorial-journal-app/tree/bug/broken-edit-with-marked-and-p-tag

Steps to repro:

- Run the app, add a post
- Click the 'edit' icon next to the new post
- Edit the text, and hit 'Update Post'
- You should see the old post text still displayed, along with the newly updated text.

**Comment by cody** [comment]
I followed your repro steps, but I could not see the bug. Wired. Maybe a bug was fixed in one of the npm packages? You could try deleting your node_modules folder to get a fresh install.

**Comment by Surreal9** [comment]
I just tried again from a different machine (also deleting node_modules and running npm install again), and I am still seeing the same  behaviour. Here is a screenshot of what I'm describing, after adding a post with content 'Test post' and then editing it to say 'Test post - updated!'

![p_tag_weird](https://cloud.githubusercontent.com/assets/4522149/11186266/82a1590a-8c46-11e5-8532-9b32f8e3d5d2.png)

I'm seeing the same thing in both Chrome and Firefox, on both a win 8 and win 10 machine. Are you sure you checked out the right branch (bug/broken-edit-with-marked-and-p-tag)? I've got it working on master by using a div instead of p tag.

**Comment by Surreal9** [comment]
I'm thinking this is a result of using marked for the inner html which is wrapping in P tags.. resulting in nested P tags, which according to http://stackoverflow.com/questions/12015804/nesting-p-wont-work-while-nesting-div-will isn't standards compliant. I will close this issue for now as I doubt React strives to handle non-compliant markup.

**Comment by cody** [comment]
Your are right, I had used the wrong branch. Now I see the problem too.

My guess is that React can't help here. The browser alters the html to make it valid. React can't  even warn properly since `dangerouslySetInnerHTML` is used.

**Comment by Surreal9** [comment]
Yes those are my thoughts as well. That's fine, thanks for looking into it!

**Comment by Ben1980** [comment]
have the same problem even with a <div> instead of <p>

**Comment by RobIsHere** [comment]
This should be reopened! The explanation here - why this issue is closed - is definitely wrong!
Yes there is a problem with standards compliance. But if standard compliance would be the reason for this issue, it would fail in dev mode, too! That's because the browser is always in production mode, whether react is in dev or not!

So there is definitely a fixable bug in react causing the dev mode to work different from production!

**Comment by Slapbox** [comment]
I have to agree with @RobIsHere. If the intended behavior is to strip invalid markup, that behavior should match in `dev` and `prod`, but it doesn't. That is definitely a problem.

**Comment by richseviora** [comment]
I agree this explanation is incorrect. I ran into this issue where a nested `p` tag was being dropped shortly after initial page render in production mode only. This issue does not appear to have been fixed as of v17.0.2.

**Comment by RobIsHere** [comment]
@bvaughn Please consider reopening this issue. We have 5 devs here confirming that there is a huge problem. 

Actually the bug is severe because it can break your react app in production while it's looking totally alright in dev mode. My case: customer told me that there are random paragraphs of a long text missing! 

So you possibly cannot assume that CI-tests would catch this either, except you're running tests with env=production.

**Comment by Jikodis** [comment]
From 2015 to almost 2022 now where I see this issue. Once you know about it, there is a workaround, but it was a mystery on a couple of our pages why content was not showing up once deployed. We have a build step that takes quite a while, so it was disappointing to see I had to figure out a fix and build again. It took a while to find this obscure cause.

However this is fixed, the end result should make it clear to the dev that they should be wary with using dangerouslySetInnerHTML on `p` tags, and what the end result will be if they do. A consistent dev/prod output for example. Even a React specific eslint warning/error would be a good first step.

Using one of Don Norman's principles of design, implementing a "constraint" would prevent this scenario and provide for a better developer and end user experience.
