### ISSUE TITLE
Since 15.2.0 TestUtils for Radios and Checkboxes Unexpected Behavior for `null` `checked` attributes

### ISSUE THREAD

**Issue by dtothefp** [facebook/react#7660]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
When using `ReactDOM.render` checkboxes with jsx attribute `checked={null}` will have a `checked` value from their DOM element of `false`. When using `TestUtils` and `TestUtils.Simulate` the same configuration above for `checked={null}` will result in `checkboxElm.checked` to be `true`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

demo here https://jsbin.com/ciwavowoqe/1/edit?html,js,console,output

**What is the expected behavior?**
expected behavior is that TestUtils would mimic actual DOM fragment, i.e. jsx property `checked={null}` results in `someCheckboxElm.checked` to be `false`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This worked in `15.1.0` but stopped working in >= `15.2.0`

**Comment by nhunzaker** [comment]
I pushed for this in https://github.com/facebook/react/pull/7530. The explanation I was given was that "null" activates uncontrolled mode for inputs, which is why you are seeing the behavior.

**Comment by dtothefp** [comment]
@nhunzaker thanks for the heads up. from reading that I'm still not clear on why I'm seeing `null` work for toggling `checked` unless I use the `TestUtils`...seems inconsistent?

**Comment by gaearon** [comment]
Switching `checked` to `null` switches your input to be [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html).
React 16 warns about this:

<img width="581" alt="screen shot 2017-10-04 at 14 09 10" src="https://user-images.githubusercontent.com/810438/31177405-d816cdee-a90d-11e7-8a27-d6da2666cabc.png">

I think what happens next is: when you click on it manually, the browser toggles it (now that it’s uncontrolled). So you see it changing. Whereas if you simulate an event with `TestUtils`, nothing happens because your click handler just switched it to uncontrolled mode but there was no real click.

As the warning suggests, don’t use `null` unless you *mean* for the component to be uncontrolled (in which case you should keep it uncontrolled for its whole lifetime).

Hope this helps!
