### ISSUE TITLE
onChange in IE11 <input type="range" />

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#8168]
Verify if it works or not.

https://github.com/mapbox/react-range

Mentioned recently here: https://github.com/facebook/react/issues/554#issuecomment-255402320

**Comment by nhunzaker** [comment]
Looks like no:

https://jsfiddle.net/69z2wepo/61407/

![change](https://cloud.githubusercontent.com/assets/590904/19887721/8312e2fe-a000-11e6-91a7-f79f193c9a1b.gif)

**Comment by spicyj** [comment]
#554. I think this is fixed in master maybe?

**Comment by cmhdave** [comment]
I do not believe [#544](https://github.com/facebook/react/issues/554) resolves this issue if the code was supposed to be released with 15.4.0 as I can confirm this is still a problem in 15.4.0.

**Comment by spicyj** [comment]
No, it's a breaking change in some cases so it is waiting for 16.0.

**Comment by Ralle** [comment]
+1.

**Comment by nhunzaker** [comment]
I can verify that this is now fixed in 16.x and 15.x, at least as far as our DOM fixtures are concerned:

![range](https://user-images.githubusercontent.com/590904/28096473-fd30c3f2-6676-11e7-8d5f-7ea82a4e3e08.gif)
