### ISSUE TITLE
Textarea placeholder isn't shown in IE 11 being rendered using React

### ISSUE THREAD

**Issue by Lkroner** [facebook/react#8546]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
Textarea does not display placeholder text initially. The placeholder text is only shown after focus and focus-away. Ie11 only. Works on all other browsers I believe, go figure.
I believe this issue [was solved before but seems to have come back](https://github.com/facebook/react/issues/6731).

PR that originally fixed the issue: https://github.com/facebook/react/pull/8020

**What is the expected behavior?**
Placeholder text should initial show on render.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.4.1, ie11. Looks like it [was working in 15.2].(http://stackoverflow.com/questions/36893449/textarea-placeholder-isnt-shown-in-ie-11-being-rendered-using-react)

**Comment by Aweary** [comment]
Thanks for the report @Lkroner, can you share a small test case reproducing the issue? You can use https://jsfiddle.net/reactjs/69z2wepo/ as a starting point.

**Comment by Lkroner** [comment]
Here you go @Aweary 😄 https://jsfiddle.net/69z2wepo/64790/

**Comment by Aweary** [comment]
Thanks! What OS are you testing on? I'm actually not able to reproduce this issue with IE11 on Windows 8.1, but I can reproduce it with IE11 on Windows 10

**Comment by Lkroner** [comment]
Yep using Browserstack, windows 10 ie11

**Comment by Aweary** [comment]
Thanks, looks like this is a separate issue with IE11 on Windows 10. I'll take a look at this when I get a chance!

**Comment by Lkroner** [comment]
Thank you! I realize it's a minor nuisance so thanks for taking a peak at it.

**Comment by gaearon** [comment]
@aweary So should this have been fixed by https://github.com/facebook/react/pull/8020 or not? Or are these separate issues?

**Comment by aweary** [comment]
@gaearon it seems like two separate issues, https://github.com/facebook/react/pull/8020 fixes the issue in IE11 on Windows 8.1 (what I tested with) but apparently it doesn't fix it for IE11 in Windows 10. I'm not entirely sure why.

**Comment by aweary** [comment]
@gaearon I'll test it all again here in a few minutes and report back

**Comment by aweary** [comment]
@gaearon tested with https://jsfiddle.net/69z2wepo/64790/ in IE11 on Windows 8 and Windows 10 and the placeholder is rendered correctly. I'm not sure what was happening before, probably user error on my part. Either way, this resolved 👍
